### PR TITLE
Correct Arch Linux dependencies installation

### PR DESCRIPTION
**Pull request by RsPlayer**
## Description

This is the correct pacman command to install needed dependencies, this installs only missing dependencies without reinstalling already existing ones.

## Modifications

- correct pacman installation

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by RsPlayer** [comment]
I have also added Vulkan wiki link since its important to compile and run the Amethyst. 

The packages I need are `vulkan-icd-loader` `vulkan-intel` since I have Intel GPU `vulkan-headers` `vulkan-validation-layers` and `vulkan-tools`

**Comment by RsPlayer** [comment]
Also Amethyst doesn't work on Wayland, I need to run it with  `WINIT_UNIX_BACKEND=x11` to make it work (issue #1846) 
Should I add it to README  and the book? the command is `WINIT_UNIX_BACKEND=x11 cargo run`

**Comment by 0x6273** [comment]
Not sure if removing `-yu` is a good idea, since many people will just copy-paste and it will fail due to the repo being out of sync.

**Comment by RsPlayer** [comment]
> Not sure if removing `-yu` is a good idea, since many people will just copy-paste and it will fail due to the repo being out of sync.

`-y` is enough to sync without updating the whole system. So I think `-Sy` would be better.

**Comment by 0x6273** [comment]
That's even worse, since it can cause a partial upgrade. https://wiki.archlinux.org/index.php/System_maintenance#Avoid_certain_pacman_commands

**Comment by RsPlayer** [comment]
I still believe `-S -needed` is the perfect one, but as you said some systems are out of sync which it won't fit for all users.

guess I'm closing this pull then.

**Pull request closed without merging**
