### PR TITLE
Port SamplerInterpolationSystem to legion macros (0.4) syntax

### PR DESCRIPTION
**Pull request by luckystreak63**
## Description
Modifications:
- SamplerInterpolationSystem now uses legion macros (0.4) syntax.
  - The `#[state]` is used to keep what looked like a previous optimization of re-using the same `Vec`s to avoid re-allocating every frame. Alternative ways to conserve this optimization without using `#[state]` could be better.
- Fixed compile errors in `animation` example.

## Motivation and Context
- Legion macros are a more concise way of writing systems
- Using legion macros internally sets an example of how they can be used
- This change could be used as an example of how to port systems to legion macros.

## How Has This Been Tested?
Compiled and ran `animation` example.

## Checklist:
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [x] My code follows the code style of this project.
- [ ] If my change required a change to the documentation I have updated the documentation accordingly.
- [x] I have updated the content of the book if this PR would make the book outdated.
- [x] I have added tests to cover my changes. (Fixed + ran animation example)
- [x] My code is used in an example. (animation)

### CODE REVIEW

**Comment by AlveLarsson** [comment]
Thanks for the PR.

Okay, so using the macros is definitively the way we want to do things, but atm legion code-gen can't re-export due to the macros expecting to import Legion from the super crate itself, I've been looking into fixing this as a part of a bigger usability improvement PR

but this can certainly be the temporary solution as it would be quite trivial to change so the examples use the re-exported macros in the amethyst::ecs namespace.

**Comment by luckystreak63** [comment]
Do you think we should wait until you complete your usability improvement PR before merging this?

I think the only debt this causes is the addition of `legion = "0.4"` to amethyst_animation's Cargo.toml, but if we merge it now we might forget to remove it later?

**Comment by AlveLarsson** [comment]
No i think this should be fine, it's something I would ensure to go over in that PR, I can't say any time frame for when I'm able to get this PR done, that's why I'm ok with this solution :)

**Comment by luckystreak63** [comment]
Does the CI only run if someone else approves it?

**Comment by AlveLarsson** [comment]
> First-time contributors need a maintainer to approve running workflows.
Yes :)

**Comment by AlveLarsson** [comment]
but the CI is somewhat broken, or rather we have some issues with clippy

**Review by AlveLarsson — APPROVED** [review]
Thanks!

**Pull request merged**
