### PR TITLE
[WIP] Never again rebase `CHANGELOG.md`

### LINKED ISSUE #1029: New changelog strategy
Our changelog is producing a lot of conflicts, leading to a lot of rebasing fun.

We can

* enforce specific commit formats to generate changelogs from (higher barrier for contributors, not what I recommend)
* continue doing what we are doing
* go through the PRs ourselves and write the changelog
* create a tool using the GitHub API that creates the changelog interactively

The tool would be my favourite. It'll be as simple as

* go through every PR from the selection
* ask if it's an addition (a), change (c) or fix (f)
* ask for a description, default to PR title
* automatically create the link and add it to the log

### PR DESCRIPTION
**Pull request by torkleyy**
## Description

This PR makes each entry of the changelog its own file such that multiple PRs do not need to rebase the `CHANGELOG.md`.

The individual entries will be merged using [`clmerge`](https://github.com/torkleyy/clmerge).

Fixes #1029 

## Modifications

* Changelog strategy changed

## TODO

* [ ] Update contribution guidelines

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Ran `cargo test --all` locally if this modified any rs files.
- [x] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [x] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Added unit tests for new APIs if any were added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by LucioFranco** [comment]
I like the idea but I'm personally not fond of having a file for each entry. I would much rather see the changelog be set via the PR title. Have you looked into that at all?

**Comment by LucioFranco** [comment]
Also, how is order maintained between changelog entries? I don't know if this is something we need but in the past, we had an order, mostly due to people adding them after each other.

**Comment by Xaeroxe** [comment]
> Also, how is order maintained between changelog entries? I don't know if this is something we need but in the past, we had an order, mostly due to people adding them after each other.

This is in my opinion unnecessary as "chronological" is arbitrary and doesn't come with any benefits for the changelog reader.

**Comment by Xaeroxe** [comment]
> I like the idea but I'm personally not fond of having a file for each entry. I would much rather see the changelog be set via the PR title. Have you looked into that at all?

Not all PRs should get a changelog entry, and even for the ones that should the PR title isn't always a good changelog entry. I'd prefer to give us the opportunity to handcraft a message for the changelog.

**Comment by LucioFranco** [comment]
> This is in my opinion unnecessary as chronological is arbitrary and doesn't come with any benefits for the changelog reader.

Sure this was a minor thing but I do generally like the order. It can be helpful as you can kinda see how things were built.

> Not all PRs should get a changelog entry, and even for the ones that should the PR title isn't always a good changelog entry. I'd prefer to give us the opportunity to handcraft a message for the changelog.

So my thoughts around this were to use labels and PR titles to generate meaningful changelogs. Depending on certain labels you can have that PR be ignored by the changelog. Now from this, we can even enforce that there is a label for the crates that are touched by this PR and this would then allow us to build changelog entries for each of amethyst crates without really having to manually curate. This would mean whoever does the merge has to make sure things look right.

**Comment by torkleyy** [comment]
That‘s all possible, but it‘s work somebody has to do. Both the setup and following all the conventions. The generators I tried so far were very slow and need more time to set up. Do you have a specific alternative in mind?

**Comment by LucioFranco** [comment]
@torkleyy what about that changelog generator you sent me a while ago? That one works quite well. I'd like to explore more options than this personally.

https://github.com/github-changelog-generator/github-changelog-generator

**Comment by LucioFranco** [comment]
second before we merge this, what is the process behind this? When does it get updated? Who does it? Does CI build it every night? etc this to me isn't clear.

**Comment by torkleyy** [comment]
Unfortunately I didn't get that one to work well with Amethyst. Last time I tried, it kept running for hours with no output so I killed it at some point.

**Comment by LucioFranco** [comment]
@torkleyy I have it working and we talk a bit on discord about this, I would like to delay the merging of this until we have found a proper way to automate and build the changelogs.

**Comment by Frizi** [comment]
Could we extend bors to read a specific entry from PR's first post and insert it as a new commit just before merging to master? That way the message is still handcrafted and present only when was explicitly written, it's all in single file in VCS and there are no conflicts about it.

**Comment by torkleyy** [comment]
> Could we extend bors to read a specific entry from PR's first post and insert it into changelog as a new commit just before merging to master?

So far, the bors team stated they don't want to mess with commits / code. And I'm not sure we want to maintain a fork.

**Comment by Frizi** [comment]
Bors is doing the merge anyway, so maybe a clever precommit hook installed on it's repo would do the job without forking.

**Comment by LucioFranco** [comment]
Not a fan of using bors honestly for this, I'd rather move the changelog to the website and have that build every 24h.

**Comment by fhaynes** [comment]
Closing this, as there doesn't seem to be consensus and we have merge conflicts again. Please open an issue for discussion if someone wants to pursue this.

**Pull request closed without merging**
