### PR TITLE
Migrate amethyst_tiles + example to legion

### PR DESCRIPTION
**Pull request by valkum**
## Description

Migrate amethyst_tiles + example to legion

Points to reconsider:
The specs TileMap used a different Storage type than the default. It used a HashMap storage, not sure if this is important for the use with legion.
The Tile prefab is not part of this PR.

## Modifications

- Needed changes for legion

## PR Checklist

By placing an x in the boxes I certify that I have:

- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Updated the content of the book if this PR would make the book outdated.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --workspace --features "empty"` (may require `cargo clean` before)
- [ ] Ran `cargo build --features "empty"`
- [ ] Ran `cargo test --workspace --features "empty"`

### CODE REVIEW

**Comment by ezpuzz** [comment]
Thanks @valkum I will be giving this a shot with my https://github.com/radium-io/sanity project as I'm planning to move it over to legion!

**Review by grzi — CHANGES_REQUESTED** [review]
Hey, just tested this, When you switch the camera, the selection/draw debug line is reverted, I guess it shouldn't be. Can you have a look ?

**Comment by ezpuzz** [comment]
@valkum I made a PR on your fork to get this up to date and passing CI.  merge at your discretion.

https://github.com/valkum/amethyst/pull/59

**Review by grzi — APPROVED** [review]

**Comment by valkum** [comment]
> Hey, just tested this, When you switch the camera, the selection/draw debug line is reverted, I guess it shouldn't be. Can you have a look ?

As mentioned in Discord, this is present in master as well. I will investigate this in a saperat issue (#2562)

**Comment by ezpuzz** [comment]
Oops this got out of date and there's a formatting failure.

@valkum could you merge legion_v2 and run cargo +nightly fmt ?

**Pull request merged**
