### PR TITLE
Update winit, glutin and gfx_window_glutin.

### PR DESCRIPTION
**Pull request by Binero**
It's not much, but I need this to be able to reuse amethyst_input outside of amethyst.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/620)

### CODE REVIEW

**Comment by jojolepro** [comment]
#613 also bumps the winit version to 0.11

**Comment by Binero** [comment]
That's why gfx_window_glutin was updated. Version 0.21 of gfx_window_glutin depends on gfx_core 0.8 or higher. Amethyst [uses 0.8](https://github.com/amethyst/amethyst/blob/d5544dc2d3e187f861d27f0a7abcbaf1a213657d/amethyst_renderer/Cargo.toml#L36).

**Comment by Binero** [comment]
@jojolepro Did not notice! Is that being close to merged? If so, it might we worth just merging that. Otherwise, it's probably better to merge this and rebase #613.

**Comment by Xaeroxe** [comment]
oh eh woops.  We got some conflicting files here.

**Comment by Binero** [comment]
(Merge conflict should be resolved)

**Comment by jojolepro** [comment]
I won't grant permission to myself cause that'd be weird ;)

**Comment by Xaeroxe** [comment]
You've been added @jojolepro

**Pull request merged**
