### PR TITLE
refactor: Move code to minterpolate, and fixing some docs

### PR DESCRIPTION
**Pull request by Rhuagh**
This has been rebased onto #563.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/566)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Unfortunately this might need to be rebased again onto develop as bors added a commit prior to merging.

**Comment by torkleyy** [comment]
Reviewed 41 of 46 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[amethyst_gltf/src/format/mod.rs, line 247 at r2](https://beta.reviewable.io/reviews/amethyst/amethyst/566#-L4y4h8vEAWp1CLqas2p:-L4y4h8vEAWp1CLqas2q:besgyfe) ([raw file](https://github.com/amethyst/amethyst/blob/bca35aa0f106efbdd8e9fdd555155ae3cf78f9b7/amethyst_gltf/src/format/mod.rs#L247)):*
> ```Rust
> }
> 
> fn map_interpolation_type<T>(ty: &gltf::animation::InterpolationAlgorithm) -> InterpolationFunction<T> where T: InterpolationPrimitive {
> ```

Formatting

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/566)*

**Comment by Rhuagh** [comment]
Rebased and fixed formatting.

---

Review status: 4 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/566#-:-L4z3Z5K3cLOI5F20Q34:bh6ckxb)*

**Comment by Rhuagh** [comment]
Review status: 4 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[amethyst_gltf/src/format/mod.rs, line 247 at r2](https://reviewable.io:443/reviews/amethyst/amethyst/566#-L4y4h8vEAWp1CLqas2p:-L4z3arO64rF70iQQ4SE:b-896fix) ([raw file](https://github.com/amethyst/amethyst/blob/bca35aa0f106efbdd8e9fdd555155ae3cf78f9b7/amethyst_gltf/src/format/mod.rs#L247)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Formatting
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/566)*

**Comment by torkleyy** [comment]
Reviewed 14 of 14 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/566)*

**Pull request merged**
