### PR TITLE
Adding loading of Mesh with any combination of separate vertex buffers

### PR DESCRIPTION
**Pull request by Rhuagh**
Fixes https://github.com/amethyst/amethyst/issues/388

### CODE REVIEW

**Comment by Rhuagh** [comment]
It's @omni-viral's macro btw, don't want to take credit for that :P

**Comment by torkleyy** [comment]
Which combinations are there we diddn't cover?

**Comment by Rhuagh** [comment]
The old implementation only have support for interleaved in the same vertex buffer.

**Comment by Rhuagh** [comment]
And the current solution also blocks the user from inventing their own vertex attributes

**Comment by Rhuagh** [comment]
I realised this is missing pass support, so I'm gonna work some more on this, so wait with reviewing it.

**Comment by torkleyy** [comment]
Wow, do we need this for every pass? And if so, can we use the new passes from the old ones?

**Comment by Rhuagh** [comment]
No, because attributes in the "old" passes are interleaved in a single vertex buffer, the new ones use a vertex buffer per attribuets.

This is ready for review now.

**Comment by omni-viral** [comment]
Related issue: https://github.com/amethyst/amethyst/issues/388

**Comment by Xaeroxe** [comment]
40 minutes, from 24 hours, 4 approvals, good enough.

bors r+

**Pull request merged**
