### PR TITLE
New Logo!

### PR DESCRIPTION
**Pull request by magnonellie**

### CODE REVIEW

**Comment by LucioFranco** [comment]
No svg 😢

**Comment by magnonellie** [comment]
@LucioFranco don't worry, it's just that we didn't actually use the SVG that was in here. It was only there as a reference for future works that need it. I'm gonna put that on the website instead along with the full branding guidelines 😄

**Comment by omni-viral** [comment]
So do we get new logo in `.svg` soon or not?

**Comment by magnonellie** [comment]
You can already get it if you need it for something 😄

Until the complete branding guidelines are done however, I don't want to allow everyone access to it, mainly because there aren't any rules in place at the moment. The branding guidelines will come together with the website revamp.

**Comment by magnonellie** [comment]
bors retry

**Comment by magnonellie** [comment]
Oh ffs Windows...

bors retry

**Comment by LucioFranco** [comment]
@magnonellie we may want to consider allowing windows to fail while its still in beta.

**Comment by magnonellie** [comment]
I was all for that but you guys down voted me saying it's super important to still have it running 😛

**Comment by azriel91** [comment]
bors retry

**Pull request merged**
