### PR TITLE
States ui hierarchy issue

### PR DESCRIPTION
**Pull request by mrhatman**
## Description

Fixed an issue where the states ui example would load incorrectly during fast transitions.

The issue was with delete hierarchy and its call to all_children_iter. https://github.com/rustgd/specs-hierarchy/issues/12

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by azriel91** [comment]
Hm, the logic is now changed to delete only the root entity. `specs-hierarchy` doesn't actually delete the child entities when the root entity is deleted -- it only removes them from the `Hierarchy` tracking.

What's the symptom / issue when transitioning quickly?

**Comment by mrhatman** [comment]
The issue was that child entity's weren't deleted when you transitioned sometimes. Especially when transitioning quickly. 

specs-hierarchy doesn't delete children? I appears to remove them in this change.

**Comment by azriel91** [comment]
> specs-hierarchy doesn't delete children? I appears to remove them in this change.

ah! I was looking at the wrong code -- it does delete children in `HierarchySystem` indeed :v:

**Comment by azriel91** [comment]
bors try

**Comment by azriel91** [comment]
ah, if you wait for the dependency bump PR, that has a fix for the current build failure (due to bumping rust version)

**Comment by azriel91** [comment]
@mrhatman could you rebase? then I think we're good to go

**Comment by mrhatman** [comment]
Yes I can,  sorry life got busy.

**Pull request merged**
