### PR TITLE
Fix CameraOrtho when coordinates are upside-down

### LINKED ISSUE #1190: CameraNormalizeMode::Contain loses space when bottom > top
version: master (77285f6a26c046ce145de69d5abc37504f1b768d) with nightly enabled

code:
```rust
.with(CameraOrtho {
    mode: CameraNormalizeMode::Contain,
    world_coordinates: CameraOrthoWorldCoordinates {
        left: 0.0,
        top: 0.0,
        right: GAME_WIDTH,
        bottom: GAME_HEIGHT,
    }
})
```

expected behaviour: any aspect ratio besides the original should have "black bars", no space should be lost

actual behaviour: when ratio is "tall", space is lost

wide window with side black bars, one tall window missing some space on either side

### PR DESCRIPTION
**Pull request by CosineP**
Upside-down coordinates would be when `bottom` is a higher value than
`top`. This is valuable since many people coming from 2D gamedev are
used to this coordinate system and want to keep it.

I have no idea if this is an actual use-case because for me, when i realized id have to flip all my assets and stuff, i just decided to get my headspace into bottom=0 mode.

Fixes #1190

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Not super sure I'm on board with making `bottom` and `top` ambiguous like this.  Perhaps we should just be flipping our coordinate system here entirely?

These assets you speak of, how did you make them?  Is our engine not accommodating common tooling?

**Comment by CosineP** [comment]
anyone who's used a 2d-first engine is probably used to a coordinate system like this:

```
0,0 ---------------------------> width
|
|
|
|
V
height                           (width, height)
```

to answer your second question, my attempt at doing this was doing an ortho with `bottom: height, top: 0.0`, buuuut, that meant that all my sprites were upside down. so i think i would have to `flip_vertical: true` them all. they're all just normal pixel-art images made in GIMP

what would "flipping our coordinate system here entirely" mean?

**Comment by Xaeroxe** [comment]
Ok it seems I misunderstood the issue a bit.  I'm going to do some more reading and thinking and then I'll get back to you on this.

**Comment by Xaeroxe** [comment]
By the way I just wanted to say your github username is adorable and I love it :)

**Comment by CosineP** [comment]
thank you!! i use it everywhere (or `cosine` when i can)

**Comment by Xaeroxe** [comment]
Can you run `cargo fmt` on this?  Apparently rustfmt doesn't like this formatting https://concourse.subnetzero.io/builds/950#L5bc8056a:8

**Comment by CosineP** [comment]
woah, that's weird, our two versions of `cargo fmt` disagree fsr? wonder if its cause im on nightly... ill fix it manually

**Comment by Xaeroxe** [comment]
Ah yeah we use stable.

**Comment by Xaeroxe** [comment]
2D games like 🙃

**Comment by torkleyy** [comment]
bors r=Xaeroxe,LucioFranco,torkleyy

**Pull request merged**
