### PR TITLE
Prefab system in Legion using Atelier assets

### PR DESCRIPTION
**Pull request by jlowry**
## Description

Use [Atelier Assets](https://github.com/amethyst/atelier-assets) and [Legion Prefab](https://github.com/kabergstrom/prefab) to replace existing asset and prefab functionality that depended on Specs.

## Motivation and Context

The old prefab system was not well suited for Legion and we have a modern assets pipeline available with https://github.com/amethyst/atelier-assets

## How Has This Been Tested?

So far with examples using the new loader.  The `material` example works to load data directly.  The `prefab` example is being updated and a new `prefab_atelier` example has been added.  The goal is example parity with the old asset code.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Updated the content of the book if this PR would make the book outdated.
- [ ] I have added tests to cover my changes.
- [x] My code is used in an example.

### CODE REVIEW

**Comment by CleanCut** [comment]
Cool! Fun to see it working. Let us know when it's ready for review.

**Comment by ezpuzz** [comment]
I've resolved the merge conflicts locally to test and that branch is here: https://github.com/radium-io/amethyst/tree/atelier-prefab

**Comment by jlowry** [comment]
> EDIT: @jlowry I've created a PR against your branch to get it up to date with legion_v2 and clear up some warnings and fix up an example.

@ezpuzz Thanks. I'll merge it today.

**Comment by jlowry** [comment]
Currently I'm working on baking prefabs that have dependencies.

Originally, I thought I could bake the prefabs in the processing queue for the prefab asset type. However this approach require tracking some state about which prefabs are dependencies and which ones are requested by the user. The examples handle it by blocking on the loader and ticking it in loop until they are loaded. But I'd rather not block.

So I'm in investigating if it's possible to move out the baking to an atelier assets importer instead.

**Comment by jlowry** [comment]
I've started writing a code path that is separate from the normal asset handling in order to handle prefabs.

I'm doing this because the prefabs have to be baked in Amethyst to suport depedencies because Atelier importers cannot reference other files. [@kabergstrom discord comment](https://discord.com/channels/425678876929163284/425679992244928512/789593710870528020)

I've just added an integration test for a basic prefab load to amethyst_assets and plan continue adding tests as I write the logic and state tracking code for the prefab baking.

**Comment by ezpuzz** [comment]
merged with upstream on https://github.com/jlowry/amethyst/pull/7 and most stuff works.  there is an atelier bug or maybe a bug with our integration that the WorldStorages update_asset is not being called when the asset finishes loading or something.  We will have to look in to it.

**Pull request merged**
