### PR TITLE
Feature/2192/fix gl rendering

### PR DESCRIPTION
**Pull request by azriel91**
## Description

Added basic GL rendering.

## PR Checklist

By placing an x in the boxes I certify that I have:

- **n/a** Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
-  **n/a** Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo +stable clippy --all --features "gl"`
- [x] Ran `cargo test --workspace --features "gl"`

### CODE REVIEW

**Comment by azriel91** [comment]
bors try

**Comment by azriel91** [comment]
Blocked on https://github.com/amethyst/builder/pull/11

**Comment by chemicstry** [comment]
> Blocked on [amethyst/builder#11](https://github.com/amethyst/builder/pull/11)

If you are not planning to test `.wasm` binary in CI, I think you can just build with `wasm-pack build --target no-modules -- --features "wasm gl"` on stable. It should compile, but will not produce atomic instructions in wasm binary.

**Pull request merged**
