### PR TITLE
refactor: Reexport shred and specs through the core crate

### PR DESCRIPTION
**Pull request by Rhuagh**
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/605)

### CODE REVIEW

**Comment by torkleyy** [comment]
I'll abstain, I'm not a fan of reexporting everything but then I know how ugly dealing with multiple versions of the same crate can be. I honestly don't know what's the best way to go here.

**Comment by jojolepro** [comment]
I approved since we use specs almost everywhere, and since we are going to make a ton of crates, having a single re-export reduces the maintenance cost.

**Comment by Rhuagh** [comment]
I debated this with myself for over a week before I created this pr. My motivation is the same as @jojolepro, you can't use anything in amethyst without specs and shred, so reexporting them makes sense

**Comment by torkleyy** [comment]
Yeah, I tend to approve, but I'll leave it up to @omni-viral, @Aceeri and @Xaeroxe to decide.

**Comment by Rhuagh** [comment]
bors r=Xaeroxe,jojolepro

**Pull request merged**
