### PR TITLE
Split resources directory

### LINKED ISSUE #1770: Split `resources` directory into `assets` and `config`
## Description

Currently, `resources` holds `display_config.ron` and potentially additional configs.

Assets are sometimes saved in `resources`, sometimes in a dedicated `assets` folder.

This issue proposes to consistently apply the following structure:

* project root
  * `assets`
    * sub asset folders (`texture`, `mesh`, `prefab`, etc.)
  * `config`
    * `display.ron`
    * `input.ron`

Note that we no longer need the `_config` suffix since the `config` folder already makes clear that those RONs are configs.

This should be applied to:

* API doc examples
* examples in the repo
* book

## Reason

The biggest reason for this change in convention is that the current convention confuses users what "resources" are. For one, we have resources in our `World`. Those are essentially globals.
Then, we have the configs and assets, which are both in `resources` - which doesn't fit very well anyway, I think.

## Impact

This change does not cause breaking changes, it merely improves the learnability and structure of our documentation, and the projects created from it.

### PR DESCRIPTION
**Pull request by DataTriny**
## Description

Fixes #1770.
This pull request splits the `/resources` directory into `/assets` and `/config` directory to better reflect their respective use.
This is my first time contributing to Amethyst, so don't hesitate to tell me if I did mistakes.

## Additions

Added an `assets` folder to examples when the `resources` directory contained files other than `display.ron` and `bindings.ron`/`input.ron`.

## Modifications

- All examples have been updated to adopt the new directory structure: `/config` for `display.ron` and `bindings.ron`, remaining files were moved to a new `/assets` directory.
- When the `main.rs` file of these examples contained a variable named something along `resources`, it has been modified to `assets_directory`.
- The book have been updated to reflect these changes (the Pong tutorial in particular).
- One or two documentation strings have been changed.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all`
- [x] Ran `cargo test --all --features "empty"`

CC @torkleyy

### CODE REVIEW

**Comment by DataTriny** [comment]
Done! Also, we should update amethyst_tools to make sure new users get the same directory structure. However, I don't know if I need to modify the `0.11.0` template, or create a new one.

**Comment by DataTriny** [comment]
@jojolepro checks have failed! Any idea why CI can't build? I didn't change my code.

**Comment by jojolepro** [comment]
bors retry

**Comment by jojolepro** [comment]
The ci fails randomly from tine to time. You can click on the "Details" button for more info when this happens.

**Pull request merged**
