### PR TITLE
feat: Add ability to control logging config via environment

### PR DESCRIPTION
**Pull request by Rhuagh**
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/916)

### CODE REVIEW

**Comment by magnonellie** [comment]
Doesn't this defeat the point of using a config object at all? I mean, what's preventing you from doing this in user code instead with the `LoggerConfig` object? I'm not against taking environment variables into account, but I don't think that logic belongs in `default()`.

**Comment by Rhuagh** [comment]
Because it's quite tedious to edit code or a config file to get more debug output. Just rerunning cargo or an executable with an env variable set is far faster

**Comment by magnonellie** [comment]
Yeah I understand that, but I still do not think this belongs in the `default()` function. There surely has to be a better way to accomplish this.

**Comment by Moxinilian** [comment]
@magnonellie What's wrong with having it be in the Default implementation?

**Comment by magnonellie** [comment]
I've never seen people put anything other than straight up default values inside of a default implementation and I suspect others have similar experiences. `Default::default()` should, in my opinion, always be predictable and return the same data. Is it possible we could put this code inside of `start_logger()` instead where it would truly be an override for whatever has been requested in code?

**Comment by Moxinilian** [comment]
While I don't mind having it in start_logger, I think it isn't inappropriate to have it in Default.
I think however that it better belongs in start_logger as there we can be sure the override is enforced.

**Comment by Rhuagh** [comment]
That better ?

**Comment by jojolepro** [comment]
Missing one review from anyone

**Comment by jojolepro** [comment]
In case you didn't see my old review

>Approving if you add docs explaining this. Thanks

So it would be nice to have either a small section in the book or in a docs/ page explaining how its used.

**Comment by Rhuagh** [comment]
Is doc on the start_logger function enough?

**Comment by jojolepro** [comment]
bors r+

hell yeah :ok_hand: 

Thanks!

**Pull request merged**
