### PR TITLE
[Fix] Ui examples prefab was broken

### PR DESCRIPTION
**Pull request by Telzhaak**
When the TextureMetadata was reworked in #981 , the `Ui` examples prefab `example.ron` had not been given the new `channel` field.

### CODE REVIEW

**Comment by Moxinilian** [comment]
I've never seen a PR with that many green check marks.

**Comment by Telzhaak** [comment]
That merge master-branch commit was unneccessary... I forgot to open this PR on a seperate branch and updated my fork :sigh:

**Comment by Rhuagh** [comment]
Conflict, please fix, and we can merge.

**Pull request merged**
