### PR TITLE
Fixed outdated code in gamedata book page

### PR DESCRIPTION
**Pull request by Pisti01**
## Description

The example code was outdated in the Custom GameData chapter

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Ran `cargo test --all` locally if this modified any rs files.
- [x] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [x] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Added unit tests for new APIs if any were added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by Pisti01** [comment]
I also found this in the same file:
```rust
.with_running::<ExampleSystem>(ExampleSystem, "example_system", &[])
```
which could be written as
```rust
.with_running(ExampleSystem, "example_system", &[])
```
Should I replace that as well?

**Comment by jojolepro** [comment]
Yes you can! ;)

**Comment by Moxinilian** [comment]
This PR is good as is, but I think this chapter would deserve the same level of automated testing we have in other chapters (with hidden context). Would you have time to do it or do you prefer we do it later?

**Comment by Pisti01** [comment]
I can try to do it but I'm unsure how can I test it

**Comment by Moxinilian** [comment]
1. Install mdbook with cargo install
2. Build Amethyst at least once
3. To test the book, simply run `mdbook test -L target/debug/deps`. If it fails, delete your target folder and rebuild Amethyst. If it still fails, ping me.

**Comment by Pisti01** [comment]
I've been looking at how the code blocks are defined in the books and most places it uses:
`rust,edition2018,no_run,noplaypen`
which causes mdbook test to skip that code.

But if I use:
`rust,no_run,noplaypen` or `rust,edition2018,noplaypen`
mdbook actually tests the code.

How should I define the code blocks?

**Comment by Moxinilian** [comment]
That's surprising. Does it give more information on why it skips it?
In the meantime, you can use `rust,no_run,noplaypen`, it's what we have been using before edition 2018.

**Comment by Pisti01** [comment]
No info, just silently skips it.

**Comment by Moxinilian** [comment]
That's weird. Drop edition then, we'll see if something weird happens later.

**Comment by Moxinilian** [comment]
I think this has been waiting long enough.
bors r=azriel91,Moxinilian

**Pull request merged**
