### PR TITLE
fix: Background music did not work because of a incorrectly setup Sys…

### PR DESCRIPTION
**Pull request by Rhuagh**
…temData

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/679)

### CODE REVIEW

**Comment by derekdreery** [comment]
FWIW this patch fixes the background music issue on my machine (linux) too.

**Comment by Rhuagh** [comment]
@torkleyy review addressed.

**Comment by Rhuagh** [comment]
Yep, I think some of us are still using rustfmt-nightly. We should be using stable rust fmt preview.

**Comment by jojolepro** [comment]
Currently using
>rustup component add rustfmt-preview

**Comment by Rhuagh** [comment]
Bors r=Xaeroxe,jojolepro

**Comment by Rhuagh** [comment]
I think it's some of our newer contributors :)

**Comment by derekdreery** [comment]
Could rustfmt be put onto the CI? I think there is a switch that makes it issue non-zero exit code if it would have made changes.

**Comment by jojolepro** [comment]
We already had a discussion on it and it was mostly a "no", because it makes it harder to create PR and to get them merged.

**Pull request merged**
