### PR TITLE
Reorganised the dependencies to combat a race condition in amethyst network

### PR DESCRIPTION
**Pull request by Machine-Hum**
## Description

Fixed race condition by reorg'ing dependency order. In addition, networking examples can now sent / receive from the client end, before the client could just send data. This makes them more comprehensive and easier for beginners to get going.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [NA] Updated the content of the book if this PR would make the book outdated.
- [NA] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [NA] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by jstnlef** [comment]
I'm not sure if we need the changes to the example files, but the changes to tcp.rs look good. Just verified that the deps are indeed backward. 👍

**Comment by azriel91** [comment]
oh, that's gonna fail. @Machine-Hum there's an extra import:

```rust
error: unused import: `std::net::TcpListener`
  --> examples/net_client/main.rs:16:5
   |
16 | use std::net::TcpListener;
   |     ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
```

**Pull request merged**
