### PR TITLE
Book and Doc checks in CI

### PR DESCRIPTION
**Pull request by ezpuzz**
## Description

This PR will keep track of status of Docs and Book for Legion branch.

### CODE REVIEW

**Comment by jojolepro** [comment]
Hello! Could you add a short description of what this pull request does, as well as its status (ready, in progress, etc)? Thank you!

**Comment by ezpuzz** [comment]
> 
> 
> Hello! Could you add a short description of what this pull request does, as well as its status (ready, in progress, etc)? Thank you!

using this as a draft to keep track of CI status of docs and books, it should be merged when green with passing docs and book.

**Comment by jojolepro** [comment]
okay thanks! :hearts:

**Comment by ezpuzz** [comment]
closing in favor of #2614

**Pull request closed without merging**
