### PR TITLE
[Review] Updated intro

### PR DESCRIPTION
**Pull request by jojolepro**
The intro felt like it was written years ago at the start of the project (it was!).
I updated it so it reflects the teamwork spirit we now have.
I also made the engine base principles easier to see and to understand.

I changed the rust installation passage so it doesn't repeat itself two lines in a row. I thought it looked weird.

Let me know what you think! :doge_face: :100:

Fixes https://github.com/amethyst/amethyst/issues/590

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/588)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
cc @amethyst/engine-devs since this is verbiage going front and center I feel like everyone should have a chance to review this.

**Comment by jojolepro** [comment]
Yes. Thanks for review!

**Comment by jojolepro** [comment]
"bump" I guess. Takes 5 minutes to review please ~u~

**Comment by jojolepro** [comment]
Thanks!

**Comment by Rhuagh** [comment]
R? @omni-viral @torkleyy

**Comment by Xaeroxe** [comment]
merging rules do permit us to r+ at this point, but since it is kind of the face of our project here I'd like to give @omni-viral and @torkleyy another 24 hours to review.

**Comment by jojolepro** [comment]
@Xaeroxe

**Comment by jojolepro** [comment]
thanks!

**Comment by torkleyy** [comment]
Oh I overlooked this, sorry.

**Pull request merged**
