### PR TITLE
fix: Log an error if a pass tries to render a mesh with incompatible vertex buffers

### PR DESCRIPTION
**Pull request by Rhuagh**
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/749)

### CODE REVIEW

**Comment by Rhuagh** [comment]
@torkleyy @Alex-Addy

**Comment by Rhuagh** [comment]
Yes, which is why we need to add tagging to the passes so we can target specific meshes for specific passes.

**Comment by Alex-Addy** [comment]
I can't speak to any other concerns, but this error message would certainly have helped me. It is still confusing looking but it would have definitely pointed me in the right direction.

**Pull request merged**
