### PR TITLE
Add Loader::load_data

### PR DESCRIPTION
**Pull request by torkleyy**
This allows loading assets from their asset data.

In order to rewrite the examples, we need to implement `Asset` for `MaterialComponent`.

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Why would an end user prefer this over Asset::load?  I thought the Asset::Data type was mostly an implementation detail.

**Comment by torkleyy** [comment]
Not really. Let's say you got the vertices and the indices of the mesh and you wanna build a mesh out of that. That's what `Loader::load_data` is for.

**Comment by torkleyy** [comment]
Travis is still working private repo's osx builds, so this might take while. But there's no rush.

**Comment by Xaeroxe** [comment]
I'm not worried about these changes so I'm gonna override bors.

**Pull request merged**
