### PR TITLE
Allow passes to fetch conflicting `SystemData`

### PR DESCRIPTION
**Pull request by torkleyy**
This is needed in order to implement caching as said by @omni-viral

### CODE REVIEW

**Comment by omni-viral** [comment]
Won't it panic in case there is real conflict?

**Comment by torkleyy** [comment]
You can have conflicts between passes and that'll be just fine I think, since they're sequential, aren't they?

**Comment by torkleyy** [comment]
Or at least that was what I had assumed, maybe I'm wrong.

**Comment by omni-viral** [comment]
No. They all run in parallel

**Comment by torkleyy** [comment]
Okay, sorry. I thought that they'd only be themselves parallel, but apperantly they're also executed in parallel.

**Pull request closed without merging**
