### PR TITLE
Add LightPrefab to GltfPrefab

### LINKED ISSUE #2348: GltfPrefab should include LightPrefab
## Feature

`GltfPrefab` works great for importing `.gltf` files but it does not import Lights from a glTF source.

The upstream glTF library [does include a way to import Lights, behind a feature flag](https://docs.rs/gltf/0.15.2/gltf/khr_lights_punctual/index.html).

## Change

The GltfPrefab should be modified to include LightPrefabs based on the data available in the upstream glTF library.

## Reason

It'd be a nice quality of life improvement.

It's also not intuitive to a new user that our glTF importer ignores lights.

## Impact

I'm pretty new to Amethyst, so I don't know how to scope this.
I don't think it would break any existing APIs, and it would only require changes to `amethyst_gltf` and maybe `amethyst_rendy`.

## Additional Notes

I've got this feature implemented on my local fork of Amethyst.
I'd be glad to use that as a staring point for a Pull Request -- I'm very open to feedback.

### PR DESCRIPTION
**Pull request by pop**
Resolves #2348

## Description

Add LightPrefabs to the GltfPrefab parser.

Edit: If any maintainers have ideas about how to unit test this let me know! I would love to add some automated tests -- I just didn't see any existing tests to add to.

## Additions

- Add a public `light: Option<LightPrefab>,` member to the `GltfPrefab` public struct.
- Add the `gltf` crate to `amethyst_rendy` with the `KHR_lights_punctual` feature enabled.
- Implement `From<khr_lights_punctual::Light<'_>>` for `amethyst_rendy::light::LightPrefab.

## Removals

N/A

## Modifications

- Enable the `KHR_lights_punctual` feature for the `gltf` dependency in `amethyst_gltf`.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by CleanCut** [comment]
This seems like a large enough change that it should have both a changelog entry and test(s).

**Comment by pop** [comment]
@CleanCut need me to make a follow-up PR for that?

**Comment by CleanCut** [comment]
@pop That would be awesome!  I'm happy to be the reviewer on that if it helps.

**Comment by pop** [comment]
@CleanCut do we have tests that I can use as a model? I'm not sure where to start for tests.

**Comment by CleanCut** [comment]
I'm afraid the only tests inside `amethyst_gltf` are [these ones in format/mesh.rs](https://github.com/amethyst/amethyst/blob/master/amethyst_gltf/src/format/mesh.rs#L254-L320).

My suggestion: If it is not straightforward to unit test something, especially if you need external files, then add an example (or multi-file example) to `amethyst_gltf/examples`. See [here](https://doc.rust-lang.org/cargo/guide/project-layout.html) and [here](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples) for more info on that.

**Pull request merged**
