### PR TITLE
[LEGION] Migrate amethyst UI to LEGION

### PR DESCRIPTION
**Pull request by grzi**
## Description

This PR migrates amethyst ui to legion, except the Prefabs part because amethyst_asset's prefabs still missing at the moment.

## Additions

- A new example called 'ui_from_code' has been added. It helps to test the different features from ui, without using prefabs. It can also be used by folks to see how to create ui from code.

## Modifications

- amethyst_ui
- examples

## PR Checklist

By placing an x in the boxes I certify that I have:

- [ ] Added unit tests for new code added in this PR.
- [X] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Updated the content of the book if this PR would make the book outdated.

If this modified or created any rs files:

- [X] Ran `cargo +stable fmt --all`
- [X] Ran `cargo clippy --workspace --features "empty"` (may require `cargo clean` before)
- [X] Ran `cargo build --features "empty"`
- [X] Ran `cargo test --workspace --features "empty"`

https://user-images.githubusercontent.com/43185161/102821443-5d765d80-43d7-11eb-85d1-44101bec09d9.mp4

### CODE REVIEW

**Comment by grzi** [comment]
Just upgraded winit to the legion_v2 version. It's working but I'm pretty sure there is a lag now on draggable and something wrong on text_editing. Those bugs weren't there before the upgrade to the current winit version.

**Comment by grzi** [comment]
Needs https://github.com/amethyst/amethyst/pull/2559 to be merged so I can fix the recent errors and stop using deprecated modifiers

**Comment by grzi** [comment]
Should be ready to review / merge now

**Review by ezpuzz — APPROVED** [review]

**Comment by ezpuzz** [comment]
Excellent work @grzi I reviewed the changes and they look good.  I know there are probably some performance or possibly other regressions compared to 0.15.3 but we can figure those out moving forward.

**Pull request merged**
