### PR TITLE
Add temp seizure warning

### PR DESCRIPTION
**Pull request by Xaeroxe**
It's silly but until we get this fixed I feel an obligation.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/652)

### CODE REVIEW

**Comment by torkleyy** [comment]
Err why is that?

**Comment by Xaeroxe** [comment]
@torkleyy the background color constantly flickers between red and white on my machine.

Can't reproduce it for @jojolepro but I can.  @jojolepro thinks it might be an issue with the parenting system but we're not sure.

**Comment by torkleyy** [comment]
Would be nice to reproduce it, not that it's a platform specific bug.

**Comment by jojolepro** [comment]
I doubt its the parenting system that causes the background issue.

**Pull request merged**
