### PR TITLE
Base 2d Render Pass

### PR DESCRIPTION
**Pull request by mrhatman**
## Description

Changed Flat 2D pass to use an extendable 2D base pass similar to base 3D to allow users to customize 2D passes in a simpler fashion. I also included a example project showcasing some of the effects that can be achieved using extendable pass. 

Please Review thoroughly and look for anything that can be improved as I want to make this robust and efficient. 

## Additions

- Base 2D
- Base 2D example

## Modifications

- Flat 2D now is implemented with Base 2D

## PR Checklist

By placing an x in the boxes I certify that I have:

- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Updated the content of the book if this PR would make the book outdated.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --workspace --features "empty"` (may require `cargo clean` before)
- [x] Ran `cargo build --features "empty"`
- [x] Ran `cargo test --workspace --features "empty"`

### CODE REVIEW

**Comment by jojolepro** [comment]
Hello! Feel free to update to the newest master branch when you have time and we'll review+merge it in the next version!
Thanks!

**Comment by jojolepro** [comment]
We still got a couple of conflicts that prevent merging. :)

**Comment by mrhatman** [comment]
Sorry, For the delay, Life has gotten hectic. I should have time this weekend to fix it up

**Comment by jojolepro** [comment]
Thank you! :hearts:

**Pull request closed without merging**
