### PR TITLE
Refactor code to be 2018 idiomatic

### PR DESCRIPTION
**Pull request by Xaeroxe**
Refactors code usage throughout the entire workspace to be 2018 idiomatic.

### CODE REVIEW

**Comment by azriel91** [comment]
Overriding the 24 hour rule:

* All PRs branched off current master will fail without this.
* We've got 2 reviews already.
* It's changing imports, not logic.

bors r=udoprog,azriel91

**Comment by azriel91** [comment]
sadness, `mdbook` compiles the crates as the 2015 edition, and still wants `extern crate _`.

**Comment by azriel91** [comment]
oh hello, we can do this:

```edition2018
// ..
```

source: https://github.com/rust-lang-nursery/mdBook/issues/812

**Comment by azriel91** [comment]
bors try

**Comment by Xaeroxe** [comment]
bors r=udoprog,azriel91

**Pull request merged**
