### PR TITLE
Update discord links

### PR DESCRIPTION
**Pull request by Xaeroxe**
We got a cool new vanity URL, let's use it!

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Minor change, and I got two reviews so

bors r+

**Comment by paezao** [comment]
@Xaeroxe it seems that the discord link is expired. I can't join :(

**Comment by Xaeroxe** [comment]
Https://discord.gg/amethyst should never expire.

What link were you hitting?

**Comment by paezao** [comment]
Interesting... it wasn't working this morning for some reason. It worked now though. Sorry for bothering!

**Pull request merged**
