### PR TITLE
Add missing logger initialization in example

### PR DESCRIPTION
**Pull request by hirschenberger**

### CODE REVIEW

**Comment by torkleyy** [comment]
You two should be friends now.

**Comment by azriel91** [comment]
image

**Comment by magnonellie** [comment]
Oh wow lol that fail though 😂

bors retry

**Comment by magnonellie** [comment]
Goddamit Apple...

bors retry

**Comment by azriel91** [comment]
bors retry

**Comment by jojolepro** [comment]
Why is it not recognizing the beta path...

bors r+

**Comment by hirschenberger** [comment]
My first PR, starts good... 🤣

**Comment by magnonellie** [comment]
Haha, so apparently this is an issue in Rust itself which is being merged pretty much as we speak. I don't know when the new release is gonna happen however: https://github.com/rust-lang/rust/issues/55817

**Comment by jojolepro** [comment]
As soon as bors merges their fix

**Comment by jojolepro** [comment]
bors r-
apparently we can only at 0:00 utc

**Comment by jojolepro** [comment]
bors r+
listen to me

**Pull request merged**
