### PR TITLE
Choose graphics backend at compile time using features

### PR DESCRIPTION
**Pull request by nchashch**
# Changes:
- Remove `GfxLoader`, `MainTargetInner`, `GfxDeviceInner`, `TextureInner`, `MeshInner`.
- Add `gfx_device::gfx_types` module, which defines `Resources`, `CommandBuffer`, `Device`, `Factory`, and `Window` types appropriate for the backend (which is set using features).

### CODE REVIEW

**Comment by kvark** [comment]
cc @msiglreith for the opposition

**Comment by msiglreith** [comment]
Indeed, I prefer to support runtime selection!
Even tough I agree on the changes for removing these wrapper types and believe that it still might be possible to provide runtime support (frontend with wrappers for the gfx types, so selecting `OpenGL`, `D3D11`, `Runtime`, etc.) after this PR.

**Comment by msiglreith** [comment]
Error log for building with `direct3d` feature enabled:
```
error[E0428]: a module named `types` has already been defined in this module
  --> src\gfx_device\gfx_types.rs:12:1
   |
2  |   mod types {
   |  _- starting here...
3  | |     extern crate gfx_device_gl;
4  | |     extern crate glutin;
5  | |     pub type Window = glutin::Window;
6  | |     pub type Resources = gfx_device_gl::Resources;
7  | |     pub type CommandBuffer = gfx_device_gl::CommandBuffer;
8  | |     pub type Factory = gfx_device_gl::Factory;
9  | |     pub type Device = gfx_device_gl::Device;
10 | | }
   | |_- ...ending here: previous definition of `types` here
11 | #[cfg(all(windows, feature="direct3d"))]
12 |   mod types {
   |  _^ starting here...
13 | |     extern crate gfx_device_dx11;
14 | |     extern crate gfx_window_dxgi;
15 | |     pub type Window = gfx_window_dxgi;
16 | |     pub type Resources = gfx_device_dx11::Resources;
17 | |     pub type CommandBuffer = gfx_device_dx11::CommandBuffer;
18 | |     pub type Factory = gfx_device_dx11::Factory;
19 | |     pub type Device = gfx_device_dx11::Device;
20 | | }
   | |_^ ...ending here: already defined

error: expected type, found module
  --> src\gfx_device\gfx_types.rs:15:23
   |
15 |     pub type Window = gfx_window_dxgi;
   |                       ^^^^^^^^^^^^^^^

error[E0243]: wrong number of type arguments: expected 1, found 0
  --> src\gfx_device\gfx_types.rs:17:30
   |
17 |     pub type CommandBuffer = gfx_device_dx11::CommandBuffer;
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 type argument
```

**Comment by Emilgardis** [comment]
There is currently no check for multiple features, and I suspected they would clash, I didn't try it out though.

**Comment by kvark** [comment]
@msiglreith so we can either have this shim as a separate layer (like you propose), or within Amethyst itself. I can see the latter being better in a way:
  - given that Amethyst has a more restricted graphics model, there are less things to have `enum` over the backends inside it, so the implementation is simpler
  - run-time backend selection is built-in and more straightforward

**Comment by msiglreith** [comment]
@kvark I'm sorry for the late response. Could you elaborate your approach more?

**Comment by kvark** [comment]
@msiglreith Since Amethyst is at higher level then gfx-rs, it simply needs less types to support different gfx-rs backends (by having `enum` of sorts in them). So that's not really "my" approach but rather - the way it is currently implemented here.

**Comment by kvark** [comment]
Ok, given that @msiglreith approves it, I'm going to merge.

**Pull request merged**
