### PR TITLE
Change proposal to define_the_sprite_sheet.md

### PR DESCRIPTION
**Pull request by JohnyProkie**
## Description

On @CleanCut [advice](https://community.amethyst.rs/t/how-can-i-know-sprite-really-got-loaded/1556/3?u=sophisticatedspoon), this PR adds clarity to declaring values for ron files, used by [SpriteGrid](https://docs.amethyst.rs/stable/amethyst_rendy/sprite/struct.SpriteGrid.html) and [SpriteList](https://docs.amethyst.rs/stable/amethyst_rendy/sprite/struct.SpriteList.html)

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [ ] Ran `cargo +stable fmt --all`
- [ ] Ran `cargo clippy --all --features "empty"`
- [ ] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by CleanCut** [comment]
Thanks for making the PR! This is a great start.

One thing we need to make clear is that it isn't a bounds problem, it's an issue with some types being wrapped in `Option<...>`.  This is a general issue with all prefabs, I believe. If the type of an argument is `Option<u32>`, for example, then you need to wrap the value in the `Some` variant.  You can see which SpriteGrid fields are wrapped in `Option` by looking at the [API documentation](https://docs.amethyst.rs/stable/amethyst_rendy/sprite/struct.SpriteGrid.html) (4 of the fields).

Alternatively, you can attack the problem by putting `#![enable(implicit_some)]` at the top of the file, which I would guess makes it so the prefab loading process attempts to wrap anything that hits a type error in `Some` and tries loading it again.

**Comment by JohnyProkie** [comment]
I see now, it seemed to me it was problem of bounds, but I wasn't able to simulate what brought me to this idea so in the end I was too quick in making an assumption.
So I changed text, but did not feel brave enough to mention it can be an issue with all prefabs.

**Comment by CleanCut** [comment]
Awesome, the information is now accurate!

Next, it would be good to combine this explanation with the previous section, while making it as short and concise as possible.  Do you mind if I push a commit with that change? Then you could take a look at it and see if it would have made sense to you.

**Comment by CleanCut** [comment]
I went ahead and pushed a commit with my suggestion for how to combine and shorten the existing and new sections. Please take a look and let me know what you think.

**Comment by JohnyProkie** [comment]
Didn't realize that, much better :+1:

**Comment by AlveLarsson** [comment]
Is this ready?

**Comment by JohnyProkie** [comment]
I removed redundant description. 
Also information about (what I consider) silent fail when value is not wrapped in `Some` or absence of `enable(implicit_some)` can be confusing. Currently we covered how spritesheet should be defined and properties that can be defined are described in documentation, so unexpected behavior caused by wrong definition is extra information, that naturally comes from context.

Another thing is failing Jenkins, but I would be really surprised if this is related to proposed change.
I would say this is ready.

**Pull request merged**
