### PR TITLE
Fix Create a Tile Map link in summary

### PR DESCRIPTION
**Pull request by Jaden-Giordano**
## Description
I forgot a `/` in the link to the `Create a Tile Map` page.

## Modifications
- [Book] Add `/` to path in `Create a Tile Map` link.

### CODE REVIEW

**Comment by CleanCut** [comment]
Ah, now that the file is properly part of the book, the book tests are failing. Hooray, CI works! 😄 

Please take a look at the failures and push up a fix!

**Comment by Jaden-Giordano** [comment]
@CleanCut Yay! Build is 🟢!

**Pull request merged**
