### PR TITLE
Fix version output, simplify arc_ball, clean up warnings

### PR DESCRIPTION
**Pull request by Xaeroxe**
cc @minecrawler

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/753)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Fixes a couple issues, cleans up some warnings, and finalizes the winit upgrade.

I don't think there's anything controversial in here, so I'm going to

bors r+

**Comment by Xaeroxe** [comment]
One more winit upgrade I'm missing

**Comment by minecrawler** [comment]
I quickly checked the things I had to change for the winit upgrade to work for me, and everything's looking fine.

**Pull request merged**
