### PR TITLE
Use global paths in SystemDesc derive

### PR DESCRIPTION
**Pull request by Awpteamoose**
## Description

Use `::amethyst::core::` or `::amethyst_core::` for paths to `SystemDesc`, `World`, `System`, etc. Also use absolute paths where possible.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by jaynus** [comment]
Tentatively approved but can you make this pass cargo fmt?

**Comment by Awpteamoose** [comment]
I did run `cargo +stable fmt --all` as requested by the checklist, not sure what you mean.

**Comment by Awpteamoose** [comment]
done

**Comment by jaynus** [comment]
https://jenkins.amethyst-engine.org/blue/organizations/jenkins/amethyst/detail/PR-1995/6/pipeline/47

Clippy is failing on unused imports in all the examples

**Comment by Awpteamoose** [comment]
done
will keep in mind running clippy on examples in the future

**Comment by azriel91** [comment]
ah, the `states_ui` example (newly merged on `master`) needs the same treatment

**Comment by Awpteamoose** [comment]
Fixed

**Comment by azriel91** [comment]
@jaynus all good to go?

**Comment by azriel91** [comment]
Rustfmt has a diff

**Comment by Awpteamoose** [comment]
Sorry, fixed again.

**Comment by azriel91** [comment]
bors try

**Comment by azriel91** [comment]
This is weird, the error message is:

```rust
message: neither amethyst nor amethyst_core found
```

Though in the snippets that fail with that, there's clearly:

```rust
extern crate amethyst;
```

I *think* mdbook creates a temporary crate for each snippet, and inserts the crate as a `[dependency]`.

**Comment by Awpteamoose** [comment]
I couldn't find a way in stable rust to tell if the code is being compiled or run from a doctest so I just naively return `quote!(::amethyst::core)` instead of panicking. It really will only be an issue if someone uses `amethyst_derive` on its own, which I doubt anyone might have a reason to.

**Pull request merged**
