### PR TITLE
Fix resize on OSX

### PR DESCRIPTION
**Pull request by Xaeroxe**
Fixes https://github.com/amethyst/amethyst/issues/547 
Fixes https://github.com/amethyst/amethyst/issues/649

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/767)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Thanks to @francesca64 for doing all of the hard work on figuring this out!

**Comment by Rhuagh** [comment]
Works, but the aspect is not kept, which I'm not sure if it's a bug or feature.

**Comment by Xaeroxe** [comment]
Yeah that matches behavior on other platforms.  Aspect resizing is simply not supported right now.

**Comment by Rhuagh** [comment]
I guess it's because our examples aren't updating the projection matrix on resize.

**Pull request merged**
