### PR TITLE
Add bundle for things we use internally, that can be stored in World

### PR DESCRIPTION
**Pull request by Rhuagh**

### CODE REVIEW

**Comment by Rhuagh** [comment]
Failed inside gl-generator crate on a gl api call. I'd say hey again.

**Comment by Rhuagh** [comment]
Try...

**Comment by Xaeroxe** [comment]
We might need to lock the crate responsible to an earlier version and inform the author that they broke SEMVER.  I don't think this is going to work.

**Comment by Xaeroxe** [comment]
I restarted our develop branch to see if we can reproduce without this PR: https://travis-ci.org/amethyst/amethyst/builds/297157029

**Comment by Xaeroxe** [comment]
If you don't get to this in about 12 hours I'll fix it tonight when I get back to a Windows PC

**Comment by Rhuagh** [comment]
Need to lock khronos_api on version 1.0

**Comment by Rhuagh** [comment]
They've been informed they broke the gfx world

**Comment by Xaeroxe** [comment]
@Rhuagh since this isn't our direct dependency I'm not sure that's the right syntax, might want to look into patch dependencies?  Anyways we'll see if this builds or not.

**Comment by Rhuagh** [comment]
It builds on my computer now, it didn't before.

**Pull request merged**
