### PR TITLE
 feat: Add rate control to animation system

### PR DESCRIPTION
**Pull request by Rhuagh**
---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/567)

### CODE REVIEW

**Comment by Rhuagh** [comment]
Rebased, and ready.

**Comment by torkleyy** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[amethyst_animation/src/resources.rs, line 228 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/567#-L53QPM6EmYEOB24bwws:-L53QPM6EmYEOB24bwwt:b88qjyv) ([raw file](https://github.com/amethyst/amethyst/blob/525289e56e4b0dec9dc9afe38ba1fd45b0b1c4cb/amethyst_animation/src/resources.rs#L228)):*
> ```Rust
>             .values_mut()
>             .filter(|t| t.state != ControlState::Done)
>         {
> ```

Can use `for_each`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/567)*

**Comment by Rhuagh** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[amethyst_animation/src/resources.rs, line 228 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/567#-L53QPM6EmYEOB24bwws:-L53bf6T_a2eTFKESAHW:b-896fix) ([raw file](https://github.com/amethyst/amethyst/blob/525289e56e4b0dec9dc9afe38ba1fd45b0b1c4cb/amethyst_animation/src/resources.rs#L228)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Can use `for_each`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/567)*

**Comment by torkleyy** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/567#-:-L54O1xS5lIftxUQOw5A:bnfp4nl)*

**Pull request merged**
