### PR TITLE
Upgrade to specs alpha4

### PR DESCRIPTION
**Pull request by Xaeroxe**
alpha4 is being treated as a patch version, so this will need to merge as soon as it compiles on CI.  Until we do this every build of the develop branch is going to fail.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/674)

### CODE REVIEW

**Comment by Rhuagh** [comment]
Aha, I'll need to fix my incoming pr then because I did this in there :)

**Comment by Xaeroxe** [comment]
@Rhuagh woops, sorry :P

**Comment by torkleyy** [comment]
Make sure to lock the version with =0.11-alpha4 so it doesn't break again.

**Pull request merged**
