### PR TITLE
Allow more encodings for text assets and configs

### PR DESCRIPTION
**Pull request by Blisto91**
## Description

This PR allows a few more encoding variants to be used when using text based config files and assets.

Specifically this will try to detect UTF-8-BOM and UTF-16-BOM by BOM sniffing and internally convert them to regular UTF-8 before being deserialized.
If no BOM's are present then the raw bytes are passed through.
Since this is a simple addition that only handles the cases of UTF-8 & UTF-16 with BOM it means that if a file is encoded in UTF-16 without BOM it still won't work, as before. UTF-32 is not supported by this crate at all.

This change should be a non breaking improvement.
It also shouldn't pose a problem for any other formats that might be used in the future since UTF-8 is standard in rust and i except all crates that handle text bytes to support it out of the box.
I have also verified this up against the changes in [PR #2401](https://github.com/amethyst/amethyst/pull/2401).

Further improvements can probably be made for this in the future.
Software that support UTF-16 without BOM usually try and make a best guess with some heuristics and are fairly good at it. But it isn't a guarantee. 
An extra option would be to look for encoding labels if present.

Fixes [#2463 ](https://github.com/amethyst/amethyst/issues/2463) 
Possible fix for [#2386](https://github.com/amethyst/amethyst/issues/2386)

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Updated the content of the book if this PR would make the book outdated.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --workspace --features "empty"` (may require `cargo clean` before)
- [x] Ran `cargo build --features "empty"`
- [x] Ran `cargo test --workspace --features "empty"`

### CODE REVIEW

**Review by CleanCut — APPROVED** [review]
Looks solid.

I suggest adding a test or two.

**Comment by Blisto91** [comment]
Never written a test before but i could probably figure it out.

Unsure how attack it tho since i just pushed it into the existing load function and i guess we want to test that the decoding works and not the config deserialization?
Should this stuff be a separate function? It's quite simple right now but could be expanded.

**Comment by CleanCut** [comment]
We don't need to test the library's decoding functionality, just our usage of it.

I think for `amethyst_assets` it would be more than sufficient to just duplicate [this test](https://github.com/amethyst/amethyst/pull/2487/files#diff-f8945f1ce77d19a1f8eb29b0886acea7R94-R105) and its associated asset file, once each for UTF-8-BOM and UTF-16-BOM.

`amethyst_config` should really have similar three tests, but as it doesn't have any at all yet, which makes it harder.  I'll leave it up to you for whether you think it's worth the effort to figure out a good set of unit tests to write up or not.

**Comment by CleanCut** [comment]
And just to be clear, if writing tests is going to be a big obstacle for you, I'd rather go ahead and merge than leave this hanging.  If you _are_ up to writing tests, that'd be a clear value-add.

**Comment by Blisto91** [comment]
I'll read a bit into it and come back to you :)

**Comment by Blisto91** [comment]
@CleanCut  First attempt!
If there's anything i should do differently or any conventions i'm not following then please tell. :)

**Comment by CleanCut** [comment]
The `amethyst_config` tests look good to me. I verified that the encodings didn't get mangled by Git.  👍

**Comment by Blisto91** [comment]
@CleanCut sorry for the delay here!
Sleep have not been agreeing with me again. 
Will try and include the asset tests this week.

**Comment by Blisto91** [comment]
@CleanCut Added tests for text assets.
More or less the same as with config

**Comment by CleanCut** [comment]
@Blisto91 LGTM. I'm hesitating to merge because I don't want to add any more burden to the legion effort.

**Review by jojolepro — APPROVED** [review]

**Comment by jojolepro** [comment]
Please resolve the conflicts and we can merge. Thank! :hearts:

**Comment by Blisto91** [comment]
Rebased, resolved and squashed.
Hope it didn't mess anything up. Still a newb with git in general.

**Comment by jojolepro** [comment]
Thanks!
bors r+

**Comment by Blisto91** [comment]
bors r-

Just noticed i accidently added the logs crate back into amethyst_config cargo.toml

**Comment by Blisto91** [comment]
Fixed.
Guess that is a downside of a rebase. 😁 

bors r+

**Comment by Blisto91** [comment]
Looks like the atelier tests randomly fail on Mac which might be a race condition from my naïve understanding of the the trace and debug info?
[Dunno if this atelier-assets PR will fix it.](https://github.com/amethyst/atelier-assets/pull/67)

**Comment by ezpuzz** [comment]
> 
> 
> Still failed. Tho this time on nightly which is allowed hehe.
> 
> Looks like the atelier tests randomly fail on Mac which might be a race condition from my naïve understanding of the the trace and debug info?
> [Dunno if this atelier-assets PR will fix it.](https://github.com/amethyst/atelier-assets/pull/67)

@kabergstrom has fixed it on another atelier branch, we can ignore those failures for now

**Pull request merged**
