### PR TITLE
Bug 1740/book unsupported method

### PR DESCRIPTION
**Pull request by azriel91**
## Description

#1928, but removed the unused file.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- **n/a** Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- **n/a** Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by distransient** [comment]
Resolves #1740

**Comment by distransient** [comment]
bors retry

**Comment by azriel91** [comment]
bors retry

**Pull request merged**
