### PR TITLE
Moving images from central README.md to individual examples

### PR DESCRIPTION
**Pull request by Puciek**
## Description

I took out all the example images and moved them to their own directories, together with relevant section copy/paste as per https://github.com/amethyst/amethyst/issues/2197

## PR Checklist

By placing an x in the boxes I certify that I have:

- [X] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [X] Ran `cargo +stable fmt --all`
- [X] Ran `cargo clippy --all --features "empty"`
- [X] Ran `cargo test --all --features "empty"`

I of course welcome any additions you have relating to those readmes, and how we can make it more user friendly while I am plowing through them.

### CODE REVIEW

**Comment by ab0v3g4me** [comment]
Seems that you didn't delete the image for tile example in the README.md. And you can leave only the list of examples.

**Comment by Puciek** [comment]
@ab0v3g4me Would it make sense then to turn the list into links that go into directories, and then have a readme.md in every single example with the content?

**Comment by ab0v3g4me** [comment]
That's what i had in mind too!

**Comment by Puciek** [comment]
@ab0v3g4me have a looksie! I hope I didn't make a silly mistake somewhere with copy/paste, but now all linked examples have readme.md

**Pull request merged**
