### PR TITLE
Fix glyph rendering on metal backend.

### LINKED ISSUE #1663: [Rendy] amethyst_ui currently does not support metal
I get this problem on macOS (MBP 2017) with metal as well in master branch ref `1dd1417a7e7d2e769a48056b166f81ba2a008036`.

```
cargo run --example renderable --features metal
```

Log:
```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.10.0
[INFO][amethyst::app] Platform: x86_64-apple-darwin
[INFO][amethyst::app] Amethyst git commit: 1dd1417a7e7d2e769a48056b166f81ba2a008036
[INFO][amethyst::app] Rustc version: 1.36.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: 5187be620c76a313a19b9b596e1bce3a80a345dd
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_factory::factory] Physical devices:
[
    AdapterInfo {
        name: "AMD Radeon Pro 560",
        vendor: 0,
        device: 0,
        device_type: DiscreteGpu,
    },
    AdapterInfo {
        name: "Intel(R) HD Graphics 630",
        vendor: 0,
        device: 0,
        device_type: IntegratedGpu,
    },
]
[INFO][rendy_factory::factory] Physical device picked: PhysicalDeviceInfo {
    name: "AMD Radeon Pro 560",
    features: ROBUST_BUFFER_ACCESS | DUAL_SRC_BLENDING | DRAW_INDIRECT_FIRST_INSTANCE | DEPTH_CLAMP | NON_FILL_POLYGON_MODE | SAMPLER_ANISOTROPY | FORMAT_BC | PRECISE_OCCLUSION_QUERY | VERTEX_STORES_AND_ATOMICS | FRAGMENT_STORES_AND_ATOMICS | SHADER_STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING | SHADER_CLIP_DISTANCE | SEPARATE_STENCIL_REF_VALUES | INSTANCE_RATE,
    limits: Limits {
        max_image_1d_size: 16384,
        max_image_2d_size: 16384,
        max_image_3d_size: 2048,
        max_image_cube_size: 16384,
        max_image_array_layers: 2048,
        max_texel_elements: 268435456,
        max_uniform_buffer_range: 1073741824,
        max_storage_buffer_range: 1073741824,
        max_push_constants_size: 4096,
        max_memory_allocation_count: 18446744073709551615,
        max_sampler_allocation_count: 18446744073709551615,
        max_bound_descriptor_sets: 256,
        max_per_stage_descriptor_samplers: 16,
        max_per_stage_descriptor_uniform_buffers: 31,
        max_per_stage_descriptor_storage_buffers: 31,
        max_per_stage_descriptor_sampled_images: 128,
        max_per_stage_descriptor_storage_images: 128,
        max_per_stage_descriptor_input_attachments: 128,
        max_per_stage_resources: 256,
        max_descriptor_set_samplers: 0,
        max_descriptor_set_uniform_buffers: 0,
        max_descriptor_set_uniform_buffers_dynamic: 0,
        max_descriptor_set_storage_buffers: 0,
        max_descriptor_set_storage_buffers_dynamic: 0,
        max_descriptor_set_sampled_images: 0,
        max_descriptor_set_storage_images: 0,
        max_descriptor_set_input_attachments: 0,
        max_vertex_input_attributes: 31,
        max_vertex_input_bindings: 31,
        max_vertex_input_attribute_offset: 255,
        max_vertex_input_binding_stride: 256,
        max_vertex_output_components: 16,
        max_patch_size: 0,
        max_geometry_shader_invocations: 0,
        max_geometry_input_components: 0,
        max_geometry_output_components: 0,
        max_geometry_output_vertices: 0,
        max_geometry_total_output_components: 0,
        max_fragment_input_components: 0,
        max_fragment_output_attachments: 0,
        max_fragment_dual_source_attachments: 0,
        max_fragment_combined_output_resources: 0,
        max_compute_shared_memory_size: 0,
        max_compute_work_group_count: [
            16,
            16,
            16,
        ],
        max_compute_work_group_invocations: 0,
        max_compute_work_group_size: [
            64,
            64,
            64,
        ],
        max_draw_indexed_index_value: 0,
        max_draw_indirect_count: 0,
        max_sampler_lod_bias: 0.0,
        max_sampler_anisotropy: 16.0,
        max_viewports: 1,
        max_viewport_dimensions: [
            16384,
            16384,
        ],
        max_framebuffer_extent: Extent {
            width: 16384,
            height: 16384,
            depth: 2048,
        },
        min_memory_map_alignment: 0,
        buffer_image_granularity: 1,
        min_texel_buffer_offset_alignment: 256,
        min_uniform_buffer_offset_alignment: 256,
        min_storage_buffer_offset_alignment: 256,
        framebuffer_color_samples_count: 5,
        framebuffer_depth_samples_count: 5,
        framebuffer_stencil_samples_count: 5,
        max_color_attachments: 4,
        standard_sample_locations: false,
        optimal_buffer_copy_offset_alignment: 256,
        optimal_buffer_copy_pitch_alignment: 4,
        non_coherent_atom_size: 4,
        min_vertex_input_binding_stride_alignment: 4,
    },
}
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_factory::factory] Queues: [
    (
        FamilyId {
            index: 0,
            device: DeviceId {
                id: 0,
                instance: InstanceId {
                    id: 0,
                },
            },
        },
        1,
    ),
]
[INFO][rendy_factory::factory] Heaps: [
    18446744073709551615,
    1073741824,
]
Types: [
    (
        DEVICE_LOCAL,
        0,
        HeapsConfig {
            linear: None,
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 33554432,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        CPU_VISIBLE | COHERENT,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        DEVICE_LOCAL | CPU_VISIBLE,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
    (
        DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED,
        1,
        HeapsConfig {
            linear: Some(
                LinearConfig {
                    linear_size: 67108864,
                },
            ),
            dynamic: Some(
                DynamicConfig {
                    block_size_granularity: 256,
                    max_chunk_size: 8388608,
                    min_device_allocation: 1048576,
                },
            ),
        },
    ),
]
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(0)', properties: 'DEVICE_LOCAL' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 33554432,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(1)', properties: 'CPU_VISIBLE | COHERENT' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(1)', properties: 'CPU_VISIBLE | COHERENT' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(2)', properties: 'DEVICE_LOCAL | CPU_VISIBLE' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(2)', properties: 'DEVICE_LOCAL | CPU_VISIBLE' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
[INFO][rendy_memory::allocator::linear] Create new 'linear' allocator: type: 'MemoryTypeId(3)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED' config: 'LinearConfig {
    linear_size: 67108864,
}'
[INFO][rendy_memory::allocator::dynamic] Create new allocator: type: 'MemoryTypeId(3)', properties: 'DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED' config: 'DynamicConfig {
    block_size_granularity: 256,
    max_chunk_size: 8388608,
    min_device_allocation: 1048576,
}'
thread '<unnamed>' panicked at 'Failed to create glyph texture: ErrorMessage { msg: "Format R8Srgb is not supported and no suitable conversion found." }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

_Originally posted by @BrianMWest in https://github.com/amethyst/amethyst/issues/1643#issuecomment-496347768_

### PR DESCRIPTION
**Pull request by Frizi**
## Description

Now glyph texture is using metal compatible pixel format and swizzle. Black rgb part of texture is biased to white in the shader instead, which required additional attribute. Final solution should be cross-platform.

Fixes #1663

### CODE REVIEW

**Comment by termhn** [comment]
Overall LGTM. Seems like that the color bias could be a uniform or even specialization constant, no?

**Comment by Frizi** [comment]
@termhn It could be both indeed, but it would be a bit harder to add on the cpu side. I just went for the easiest thing right now really.

**Comment by Frizi** [comment]
bors r=termhn,torkleyy

**Comment by rayrrr** [comment]
From line 491 of the Jenkins traceback:

`error: failed to write /tmp/rustc2mH10W/rust.metadata.bin: No space left on device (os error 28)`

Seems like this is a resource constraint issue, not an application code issue.

**Comment by torkleyy** [comment]
Fixed.
bors r=termhn,torkleyy

**Comment by rayrrr** [comment]
Awesome! Thanks @torkleyy for the quick fix!

**Comment by torkleyy** [comment]
@rayrrr Thank @Frizi, I just cleared the build server :smile:

**Comment by rayrrr** [comment]
Thank you @Frizi for the bug fix! @torkleyy I was just thanking you for getting the build to succeed after noting the out of memory situation. :)

**Pull request merged**
