### PR TITLE
Add load_from_data_async to Asset Loader

### PR DESCRIPTION
**Pull request by Friz64**
## Description

This PR enables users to asynchronously compute an asset by passing a loading function that gets called inside the asset loader threadpool.

## Additions

- Add `load_from_data_async` to `AssetLoaderSystemData`
- Add `load_from_data_async` to `Loader`

## PR Checklist

By placing an x in the boxes I certify that I have:

- [ ] Ran `cargo test --all` locally if this modified any rs files. 
(This took too much ram and crashed for me)
- [x] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [ ] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new APIs if any were added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by torkleyy** [comment]
> (This took too much ram and crashed for me)

Wow, never heard that before. Doesn't rustc track RAM usage?

**Comment by azriel91** [comment]
> > (This took too much ram and crashed for me)
> 
> Wow, never heard that before. Doesn't rustc track RAM usage?

It doesn't track RAM usage sadly -- my laptop with 8 GB RAM sometimes needs `-j 4` when compiling to not fail with out of memory.

**Comment by Friz64** [comment]
I have 8 GB of RAM + 4 GB Swap and 12 threads and i think its because the build invokes too many gcc processes.

**Comment by Friz64** [comment]
I've been wanting to start work on the documentation and tests but am unsure about the process because `load_from_data` (non-async) doesn't have any more documentation or tests than my async function.

**Pull request merged**
