### PR TITLE
Create rust ci actions workflow

### PR DESCRIPTION
**Pull request by CleanCut**
Experimenting with GitHub Actions as a CI solution, take 2.

This is a work-in-progress (not ready for review), but I'm not going to put this in "Draft" mode in case that's what's broke my last attempt.

### CODE REVIEW

**Comment by CleanCut** [comment]
@fhaynes Does Actions need to be "enabled" on the `amethyst` org or the `amethyst/amethyst` repo or something?

**Comment by fhaynes** [comment]
Actions is enabled for all repos in the organization, it says. There are no
runners configured, though.

**Comment by fhaynes** [comment]
Did you try going through https://github.com/amethyst/amethyst/actions/new ?

**Comment by fhaynes** [comment]
Looking at main.yml, I think this is telling it to only run on the default branch, which in our case right now would be `master`, or PRs against `master`. Let's see if giving it an approving review helps.

**Comment by fhaynes** [comment]
I changed the on push trigger to be `*` and not just $default-branch, and it seems to at least recognize that it should trigger now.

**Comment by CleanCut** [comment]
@fhaynes  What it recognizes is that the file is now syntactically invalid. 🤣

image

**Comment by CleanCut** [comment]
I'm switching the build to a no-op `echo` command and merging this into master to see if we can get actions working at all.

**Pull request merged**
