### PR TITLE
Move windows to allowed failures.

### PR DESCRIPTION
**Pull request by Xaeroxe**
I'm tired of this causing problems, so I'm opening this.

### CODE REVIEW

**Comment by jojolepro** [comment]
lol rust is just generally buggy on windows and mac

**Comment by Xaeroxe** [comment]
Hard disagree, the travis servers are just bad.  I do pretty much 100% of my Rust dev on windows

However that's neither here nor there.

**Comment by jojolepro** [comment]
Well my rust compiler freezes 50% of the time on both my windows installs.

**Comment by Xaeroxe** [comment]
You're probably engaging select mode for cmd or powershell on accident.  If you just hit Escape it leaves it.  select mode is quite possibly the single worst shell feature I've ever seen, but that is most definitely not rust's fault :P

**Comment by torkleyy** [comment]
But this effectively disables all checks for Windows?

**Comment by Xaeroxe** [comment]
Yeah it does, and that's ok for now in my opinion.  We don't write enough platform specific code to be losing as much time to these failures as we are.  As soon as the travis windows implementation is stable we'll move it out of allowed failures.

**Comment by Xaeroxe** [comment]
bors try

**Comment by Xaeroxe** [comment]
bors retry

**Comment by Xaeroxe** [comment]
Huh.  I guess you can only do that once per PR?

**Comment by Xaeroxe** [comment]
Ok, had to wait for the last one to fail.  Let's try again with the macro_use fix applied.

bors try

**Comment by jojolepro** [comment]
With rendy and laminar getting more integrated, youll have plenty of platform specific bugs popping up. There are already runtime bugs on windows currently...

**Comment by Xaeroxe** [comment]
Travis wouldn't be able to catch that anyways, it would only catch compile errors.

Perhaps during the rendy and laminar integration we could open the travis builds ourselves and look to see if windows is passing.  If it fails due to typical travis operational problems then we'll have to test it on windows manually.

**Comment by Xaeroxe** [comment]
Our builds have errored out 13 times since we added Windows to travis, not including the trying branch.

**Comment by Xaeroxe** [comment]
On another note, if we get through the entire rendy integration without once manually testing on Windows and making sure rendering output looks the way we want it to then we are failing at our jobs.

**Comment by jojolepro** [comment]
Are you counting that time when I restarted the mac builds 6 times in a row because rustc broke? Windows was enabled at that time.

**Comment by Xaeroxe** [comment]
@jojolepro if you only restarted the mac build and didn't send in a whole new commit then no I'm not counting that.

**Comment by jojolepro** [comment]
I would start it, then it would fail to get the rustup update. It usually did push a commit to trying.

**Comment by Xaeroxe** [comment]
Can you link the PR?  I'll double check my numbers.

**Comment by Xaeroxe** [comment]
Oh might not be necessary as I was only counting the staging branch

**Comment by Xaeroxe** [comment]
Ok so after a recount where I was only counting builds that Windows had a timeout on, we got 10 failures.

**Comment by Xaeroxe** [comment]
@jojolepro @torkleyy if you two feel like I haven't addressed your concerns can you please re-iterate which concerns remain?  If you do feel like I've addressed them then can I please get an approval?

**Comment by torkleyy** [comment]
I don't have a problem with commenting "bors r+" multiple times, but with having to fix master because a PR broke it. That's why I'm unsure.

**Comment by magnonellie** [comment]
For the record, doing this would significantly speed up merge times because we aren't gonna be hitting the 5 runner limit for required jobs.

**Comment by torkleyy** [comment]
I see your point, but we don't need merges to happen faster now. If it becomes a problem in the future (because we are building up a backlog due to Windows bugs, which should be solved after the beta), we can still look into this again.

I see the approvals so far are in favour of this, and if there are approvals from the other members I'll simply abstain.

**Comment by Xaeroxe** [comment]
It's not ideal, but it's temporary.  So I'll go ahead and

bors r+

**Pull request merged**
