### PR TITLE
Extracted some common code in input handler tests.

### PR DESCRIPTION
**Pull request by azriel91**
Issue #1249

* moved the `sets_are_equal` function down (so that the first thing you see is a `#[test]`)
* abstracted the event creation logic, should make it easier to see what the test is doing
* made a `HIDPI` constant (no longer have to check what `1.0` means)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
I found myself with some free time to add another unit test. Hope you don't mind me slipping a commit into this PR.

**Comment by Xaeroxe** [comment]
Ok, I screwed that up a bit, for a bit, but I fixed it. Let's just agree Jake should stop pushing commits to other people's forks for a bit.

**Comment by azriel91** [comment]
@Xaeroxe by all means, hijack this! 😄
I don't mind PR hijackings as long as we're doing the same thing ⚔️

**Comment by Xaeroxe** [comment]
@azriel91 hijacked away :) I added some more unit tests.

**Comment by azriel91** [comment]
✅ to @Xaeroxe's changes (can't approve a self-opened PR).

also,

> I don't mind if you hijack the car I'm driving, as long as you're a better driver and we're going to the same destination 😛

**Comment by Xaeroxe** [comment]
Heh thanks for cleaning up my mess, though it seems we missed `ControllerButtonReleased` docs.

**Pull request merged**
