### PR TITLE
Use VecStorage for small components and HashStorage for Camera

### PR DESCRIPTION
**Pull request by Xaeroxe**
This optimization improves server performance by optimizing storages.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/501)

### CODE REVIEW

**Comment by Aceeri** [comment]
I don't think changing DenseVecStorage to a HashMap will have performance benefits (probaby the other way around)

**Comment by Xaeroxe** [comment]
There's typically only one camera in a game, if hashmap storage isn't useful here it's literally not useful anywhere.

**Comment by torkleyy** [comment]
Its memory consumption is lower, that's the main benefit.

**Comment by Rhuagh** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by torkleyy** [comment]
As for very rare components, this is an idea I had a few days ago:

```rust
#[derive(Derivative)]
#[derivative(Default(bound = ""))]
pub struct SmallVecStorage<A: Array, T> {
    storage: SmallVec<A>,
    marker: PhantomData<T>,
}

impl<A, T> UnprotectedStorage<T> for SmallVecStorage<A, T>
where
    A: Array<Item = (T, u32)>,
{
    unsafe fn clean<F>(&mut self, _: F) where
        F: Fn(Index) -> bool {
    }

    unsafe fn get(&self, id: Index) -> &T {
        &self.storage.iter().find(|x| x.1 == id).unwrap().0
    }

    unsafe fn get_mut(&mut self, id: Index) -> &mut T {
        &mut self.storage.iter_mut().find(|x| x.1 == id).unwrap().0
    }

    unsafe fn insert(&mut self, id: Index, value: T) {
        self.storage.push((value, id));
    }

    unsafe fn remove(&mut self, id: Index) -> T {
        let pos = self.storage.iter().position(|x| x.1 == id).unwrap();

        self.storage.remove(pos).0
    }
}
```

But I'm not sure if it's worth it. It's probably useful if you have exactly two components of that type, but otherwise its performance is very bad (O(n)).

**Comment by Xaeroxe** [comment]
Honestly working on this PR revealed to me these are all micro-optimizations that don't actually have much impact on the final game.  I half considered closing this because I don't want to ask people to review something so ineffective.  I tried to benchmark this and I actually couldn't prove it was useful because the impact was that small.

**Comment by torkleyy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[amethyst_animation/src/resources.rs, line 23 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-XTFuw55BHjbgp91vz:-L-XTFuw55BHjbgp91w-:bygfdp7) ([raw file](https://github.com/amethyst/amethyst/blob/2a1a1e60472991db6c14acc4960030ad896b8abc/amethyst_animation/src/resources.rs#L23)):*
> ```Rust
> /// it is attached to.
> #[derive(Debug, Clone, Serialize, Deserialize)]
> pub struct Sampler {
> ```

How is this a small component? If I say small, I mean something like 16 bytes at maximum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by Xaeroxe** [comment]
*[amethyst_animation/src/resources.rs, line 23 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-XTFuw55BHjbgp91vz:-L-XTkyQTN46WFGc_zVc:b-5mryu) ([raw file](https://github.com/amethyst/amethyst/blob/2a1a1e60472991db6c14acc4960030ad896b8abc/amethyst_animation/src/resources.rs#L23)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

How is this a small component? If I say small, I mean something like 16 bytes at maximum.
</blockquote></details>

Because the thing I changed was the Handle storage.  Handles are small.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by torkleyy** [comment]
*[amethyst_animation/src/resources.rs, line 23 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-XTFuw55BHjbgp91vz:-L-XTvXfGUluXJa9sV01:b-t45em0) ([raw file](https://github.com/amethyst/amethyst/blob/2a1a1e60472991db6c14acc4960030ad896b8abc/amethyst_animation/src/resources.rs#L23)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

Because the thing I changed was the Handle storage.  Handles are small.
</blockquote></details>

Err oops sorry, then you're right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by torkleyy** [comment]
I'd also vote to close this.

**Comment by Xaeroxe** [comment]
Closing then.

- This optimization is nearly useless
- Having this code written the way it is might actually cause problems later on when the components are larger.

**Comment by Xaeroxe** [comment]
So this testing was with a render loop.  @torkleyy 's work in https://github.com/lschmierer/ecs_bench/pull/28 showed that without a render loop there is actually something to be gained here though.  That might actually matter when we start deploying Amethyst in server environments so I'm re-opening this.

**Comment by torkleyy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[amethyst_assets/src/asset.rs, line 25 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-zx-2xo7S-lzrOxyvY:-L-zx-2xo7S-lzrOxyvZ:b-ig1chy) ([raw file](https://github.com/amethyst/amethyst/blob/2a1a1e60472991db6c14acc4960030ad896b8abc/amethyst_assets/src/asset.rs#L25)):*
> ```Rust
>     type Data: Send + Sync + 'static;
> 
>     /// The ECS storage type to be used. You'll want to use `DenseVecStorage` in most cases.
> ```

That's one of the issues with this PR: I'm not sure if this is true. A `Handle` is more than 2 * word size. 

---

*[amethyst_renderer/src/cam.rs, line 91 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-zxKo15iGzU0ud0AXE:-L-zxKo15iGzU0ud0AXF:bitq4k9) ([raw file](https://github.com/amethyst/amethyst/blob/5f4b81936e9deba9a4f8a73c5cc0031c9c2c67a0/amethyst_renderer/src/cam.rs#L91)):*
> ```Rust
> 
> impl Component for Camera {
>     type Storage = HashMapStorage<Self>;
> ```

LGTM, this is good for memory consumption.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by Xaeroxe** [comment]
*[amethyst_assets/src/asset.rs, line 25 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-zx-2xo7S-lzrOxyvY:-L0-0MmExa0nqt06P62_:b-a6dygh) ([raw file](https://github.com/amethyst/amethyst/blob/2a1a1e60472991db6c14acc4960030ad896b8abc/amethyst_assets/src/asset.rs#L25)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

That's one of the issues with this PR: I'm not sure if this is true. A `Handle` is more than 2 * word size. 
</blockquote></details>

When I run this code:

```rust
extern crate amethyst;

use amethyst::assets::Handle;

fn main() {
    println!("Size of handle: {}", ::std::mem::size_of::<Handle<usize>>());
    println!("Size of usize: {}", ::std::mem::size_of::<usize>());
}

```

I get this output:

```
Size of handle: 8
Size of usize: 8
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by Xaeroxe** [comment]
*[amethyst_assets/src/asset.rs, line 25 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-zx-2xo7S-lzrOxyvY:-L0-0g1ZtNsONO6EoZtT:bpn4m1l) ([raw file](https://github.com/amethyst/amethyst/blob/2a1a1e60472991db6c14acc4960030ad896b8abc/amethyst_assets/src/asset.rs#L25)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

When I run this code:

```rust
extern crate amethyst;

use amethyst::assets::Handle;

fn main() {
    println!("Size of handle: {}", ::std::mem::size_of::<Handle<usize>>());
    println!("Size of usize: {}", ::std::mem::size_of::<usize>());
}

```

I get this output:

```
Size of handle: 8
Size of usize: 8
```
</blockquote></details>

IIRC Handle is just an Arc, which is just a pointer, which is usize.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by torkleyy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[amethyst_assets/src/asset.rs, line 25 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-zx-2xo7S-lzrOxyvY:-L0-1C41Vuszb5pFZkpa:b1l2gx2) ([raw file](https://github.com/amethyst/amethyst/blob/2a1a1e60472991db6c14acc4960030ad896b8abc/amethyst_assets/src/asset.rs#L25)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

IIRC Handle is just an Arc, which is just a pointer, which is usize.
</blockquote></details>

OK, I'm stupid. Didn't take into account that the counters are all on the heap, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by Xaeroxe** [comment]
bor r+

**Comment by Xaeroxe** [comment]
*[amethyst_renderer/src/cam.rs, line 91 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/501#-L-zxKo15iGzU0ud0AXE:-L05IPRhhYU0j1PIxoGJ:b-ahz6y4) ([raw file](https://github.com/amethyst/amethyst/blob/5f4b81936e9deba9a4f8a73c5cc0031c9c2c67a0/amethyst_renderer/src/cam.rs#L91)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

LGTM, this is good for memory consumption.
</blockquote></details>

Reviewable.io isn't letting bors go until I respond to this I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/501)*

**Comment by Xaeroxe** [comment]
Overriding, reviewable.io and bors aren't cooperating right now.

**Pull request merged**
