### PR TITLE
Use a nicer sound for a score

### PR DESCRIPTION
**Pull request by derekdreery**
Although I have great respect for the original sfx used for a score, I thought I'd suggest a slightly less "suprising" sound. ;)

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/710)

### CODE REVIEW

**Comment by torkleyy** [comment]
I think we have a file where we list all the sources of the assets and there licenses.

**Comment by derekdreery** [comment]
I just made it in LMMS - and absolutely no copywrite at all

**Comment by derekdreery** [comment]
Do you know where that file is - a quick search didn't yield it.

**Comment by torkleyy** [comment]
There is one under https://github.com/amethyst/amethyst/blob/develop/examples/assets/texture/LICENSE_TEXTURES.txt but that's not really enough :(

**Comment by derekdreery** [comment]
I'll create one for audio.

**Comment by derekdreery** [comment]
I've push a file and filled in the licenses I can.

**Comment by derekdreery** [comment]
I'm just replacing a sound I find a bit unpleasant lol, I'd suggest leaving actually good sound effects to a seaparate PR.

**Comment by derekdreery** [comment]
The failure is spurious. Don't know how to trigger a re-run

**Comment by Rhuagh** [comment]
Bors try

**Comment by Xaeroxe** [comment]
bors retry

**Pull request merged**
