### PR TITLE
Upgrade shred to 0.9 in amethyst_network

### PR DESCRIPTION
**Pull request by aeubanks**

### CODE REVIEW

**Comment by TimonPost** [comment]
Thanks for the PR, although it is not needed because it is removed by this [PR](https://github.com/amethyst/amethyst/pull/1917/files)

**Comment by distransient** [comment]
This dependency actually isn't used funnily enough, so it could just be removed in its current state (along with shrev, although its usage [here](https://github.com/amethyst/amethyst/blob/master/amethyst_network/src/connection.rs#L4) should instead refer to the shrev provided through the specs re-exposed in amethyst-core).

@TimonPost what's the state of that rewrite? Should we expect it to be ready for 0.14?

**Comment by TimonPost** [comment]
Ask @jstnlef, I believe it is but could be wrong

**Comment by distransient** [comment]
👍 will close this for now.

**Pull request closed without merging**
