### PR TITLE
Removed concourse CI/CD

### PR DESCRIPTION
**Pull request by fhaynes**
The server running concourse is going away, so we need to remove this.

### CODE REVIEW

**Comment by LucioFranco** [comment]
Why is gitlab not running and concourse is 🤔

**Comment by Xaeroxe** [comment]
Not merged yet.  I don't think it takes effect until master is updated.

**Comment by LucioFranco** [comment]
As far as I know if gitlab accepts the webhooks it shouldn't pull from master unless its setup in the gitlab settings to only pull from master. This will cause issues anyways as the only way then to verify changes to the CI script will have to be done on master, which isn't a good idea.

**Comment by fhaynes** [comment]
GitLab mirrors everything; master, all branches

**Comment by fhaynes** [comment]
Ah, it is hung because there is no more .concourse.

**Pull request merged**
