### PR TITLE
Docs/update links

### PR DESCRIPTION
**Pull request by azriel91**
## Description

Updated many documentation links for website.

## PR Checklist

By placing an x in the boxes I certify that I have:

- **n/a** Ran `cargo test --all` locally if this modified any rs files.
- [x] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [x] Updated the content of the book if this PR would make the book outdated.
- **n/a** Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- **n/a** Added unit tests for new APIs if any were added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by azriel91** [comment]
this is new

```rust
error: unused attribute
   --> amethyst_error/src/lib.rs:421:9
    |
421 |         #[no_mangle]
    |         ^^^^^^^^^^^^
    |
    = note: `-D unused-attributes` implied by `-D warnings`
```

**Comment by torkleyy** [comment]
Rust nightly breakage

**Comment by torkleyy** [comment]
Should work after [this PR](https://github.com/amethyst/amethyst/pull/1616).

bors r+

**Pull request merged**
