### PR TITLE
Standardize builder naming

### PR DESCRIPTION
**Pull request by Xaeroxe**

### CODE REVIEW

**Comment by Xaeroxe** [comment]
bors r+

@torkleyy I couldn't find any methods that borrow the Builder mutably, otherwise I would have done that.

**Comment by torkleyy** [comment]
Well the idea was to add those, because we don't have them yet.

**Comment by omni-viral** [comment]
@torkleyy for each moving `with_` add mutating `add_` method?

**Comment by jojolepro** [comment]
What about ::default and ::new?
Time::default()
InputHandler::new()
LocalTransform::default()
Transform::default()
TransformSystem::new()
pass::DrawFlat::<PosNormTex>::new()
Dj::new(&output)
MaterialBuilder::new()
MeshComponent::new()
BoxedErr::new

**Comment by Xaeroxe** [comment]
@jojolepro Those are interesting and probably deserve to be addressed, but they're out of the scope of this pull request

**Comment by Xaeroxe** [comment]
Overriding.

**Pull request merged**
