### PR TITLE
Publish v0.13.1

### PR DESCRIPTION
**Pull request by distransient**
## Description

This increments the patch version of all changed crates and updates the Changelog. Crates which depend on patched crates but have not been changed I've left alone, since the only crates which truly need their hotfixes are `amethyst_locale` and `amethyst_tiles`. After this PR is approved and merged I will begin publishing 0.13.1.

### CODE REVIEW

**Comment by azriel91** [comment]
bors try
(fs race condition)

**Comment by distransient** [comment]
Alright. Time for the fun part :D

**Comment by azriel91** [comment]
ship ship :package:

**Pull request merged**
