### PR TITLE
winit 1.13.1 upgrade

### LINKED ISSUE #655: Amethyst crashes when closing pong on arch linux.
Also happens with all examples using a window I assume.
Tested on examples:
-pong
-ui

System: 
Arch Linux updated last week
Gtx 1070
Intel i7 something something

I only started to notice this issue a couple of days ago or maybe 1-2 week maximum.

Trace:
```
thread 'main' panicked at 'Failed to unfocus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 14, minor_code: 0 }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Failed to close input method: XError { description: "GLXBadDrawable", error_code: 172, request_code: 154, minor_code: 11 }', libcore/result.rs:945:5
stack backtrace:
   0:     0x55eebd724413 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h09c1ee131a74b1c4
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55eebd71ea04 - std::sys_common::backtrace::_print::h47a337b62b6d5e9e
                               at libstd/sys_common/backtrace.rs:71
   2:     0x55eebd7233dd - std::panicking::default_hook::{{closure}}::h945a649c9017832e
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:380
   3:     0x55eebd7230e2 - std::panicking::default_hook::hcc534c2d30fbcda3
                               at libstd/panicking.rs:396
   4:     0x55eebd723850 - std::panicking::rust_panic_with_hook::h09a7a3a353dc2f38
                               at libstd/panicking.rs:576
   5:     0x55eebd72370e - std::panicking::begin_panic::h8327f16bde15df70
                               at libstd/panicking.rs:537
   6:     0x55eebd723609 - std::panicking::begin_panic_fmt::h42ff1d37404632d6
                               at libstd/panicking.rs:521
   7:     0x55eebd723592 - rust_begin_unwind
                               at libstd/panicking.rs:497
   8:     0x55eebd768440 - core::panicking::panic_fmt::h0bd854df201d1baf
                               at libcore/panicking.rs:71
   9:     0x55eebd3bede7 - core::result::unwrap_failed::h0ca9cf5987517719
                               at /checkout/src/libcore/macros.rs:23
  10:     0x55eebd3bcbfb - <core::result::Result<T, E>>::expect::h1d5263fec80460fb
                               at /checkout/src/libcore/result.rs:809
  11:     0x55eebd35817c - <winit::platform::platform::x11::util::Ime as core::ops::drop::Drop>::drop::had0ba113e8882438
                               at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.12.0/src/platform/linux/x11/util.rs:409
  12:     0x55eebcda1104 - core::ptr::drop_in_place::h57e6a1117dfc2eb5
                               at /checkout/src/libcore/ptr.rs:59
  13:     0x55eebcd98918 - core::ptr::drop_in_place::h13bf5a1b09818af2
                               at /checkout/src/libcore/ptr.rs:59
  14:     0x55eebcee55f3 - <std::collections::hash::table::RawTable<K, V>>::rev_drop_buckets::h439d0279f31320bc
                               at /checkout/src/libstd/collections/hash/table.rs:894
  15:     0x55eebcef78c2 - <std::collections::hash::table::RawTable<K, V> as core::ops::drop::Drop>::drop::h8474cea0aa02ae24
                               at /checkout/src/libstd/collections/hash/table.rs:1177
  16:     0x55eebcd9e704 - core::ptr::drop_in_place::h415fdc067b8b8eb3
                               at /checkout/src/libcore/ptr.rs:59
  17:     0x55eebcdaef88 - core::ptr::drop_in_place::hccda4a7ddde4b584
                               at /checkout/src/libcore/ptr.rs:59
  18:     0x55eebcda3264 - core::ptr::drop_in_place::h6b2bd288899d36c4
                               at /checkout/src/libcore/ptr.rs:59
  19:     0x55eebcdade48 - core::ptr::drop_in_place::hc30a8d41561f659b
                               at /checkout/src/libcore/ptr.rs:59
  20:     0x55eebcd96625 - core::ptr::drop_in_place::h008a9976ab2bc81e
                               at /checkout/src/libcore/ptr.rs:59
  21:     0x55eebcda5771 - core::ptr::drop_in_place::h7fd5f23318a4b14d
                               at /checkout/src/libcore/ptr.rs:59
  22:     0x55eebcda75b4 - core::ptr::drop_in_place::h8effc0a9e9629e8c
                               at /checkout/src/libcore/ptr.rs:59
  23:     0x55eebcdb3f7c - core::ptr::drop_in_place::hfacd7d0c016dddc0
                               at /checkout/src/libcore/ptr.rs:59
  24:     0x55eebcd99c7d - core::ptr::drop_in_place::h1c872bd22108db1a
                               at /checkout/src/libcore/ptr.rs:59
  25:     0x55eebcdaec76 - core::ptr::drop_in_place::hcb61257ea0894e5c
                               at /checkout/src/libcore/ptr.rs:59
  26:     0x55eebcd921cd - <smallvec::SmallVec<A> as core::ops::drop::Drop>::drop::h59881aea51ae6d40
                               at /home/jojolepro/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.4.4/lib.rs:914
  27:     0x55eebcda3954 - core::ptr::drop_in_place::h6f18cc7b98ee6b23
                               at /checkout/src/libcore/ptr.rs:59
  28:     0x55eebcda6b2d - core::ptr::drop_in_place::h89d95e688e25db57
                               at /checkout/src/libcore/ptr.rs:59
  29:     0x55eebcda0249 - core::ptr::drop_in_place::h4f1014bed007a20c
                               at /checkout/src/libcore/ptr.rs:59
  30:     0x55eebcf2130b - pong::run::h74dfbad09e7f68cd
                               at examples/pong/main.rs:88
  31:     0x55eebcf1fcd6 - pong::main::h515cf6a6fc9c539b
                               at examples/pong/main.rs:45
  32:     0x55eebce2de21 - std::rt::lang_start::{{closure}}::h65c98fe836775e70
                               at /checkout/src/libstd/rt.rs:74
  33:     0x55eebd7234f7 - std::panicking::try::do_call::hd12baa704e255980
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:479
  34:     0x55eebd72e1ae - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  35:     0x55eebd723d13 - std::rt::lang_start_internal::h764d480f090a00ea
                               at libstd/panicking.rs:458
                               at libstd/panic.rs:358
                               at libstd/rt.rs:58
  36:     0x55eebce2de01 - std::rt::lang_start::h51b0fd672bcb8eb2
                               at /checkout/src/libstd/rt.rs:74
  37:     0x55eebcf2210d - main
  38:     0x7f6463bfcf49 - __libc_start_main
  39:     0x55eebcd49e29 - _start
  40:                0x0 - <unknown>
thread panicked while panicking. aborting.
zsh: illegal hardware instruction (core dumped)  cargo run --example pong
```

### PR DESCRIPTION
**Pull request by illis**
Fixes #655 (have tested on my Arch Linux machine). 

According to the [winit changelog](https://github.com/tomaka/winit/blob/master/CHANGELOG.md) ios needs to be handled slightly differently (I haven't tested this).

Note from Xaeroxe:
Fixes https://github.com/amethyst/amethyst/issues/515

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/698)

### CODE REVIEW

**Comment by francesca64** [comment]
> According to the winit changelog ios needs to be handled slightly differently

On Windows, macOS, X11, and Wayland, you get sent `CloseRequested` and can choose how to deal with it, and then you get `Destroyed` when you either A) drop the window, or B) the OS/WM destroys your window unexpectedly (...and we're not yet aware of any non-contrived cases where that would happen). On iOS, `CloseRequested` is never emitted, and your window may be `Destroyed` by the OS to free up memory when in the background. The important part of the semantics of the `Destroyed` event is that it's no longer safe to render to that window, and that's universal across platforms (except for on Android and Emscripten, since those backends didn't implement `Closed` to begin with, so they weren't touched by the API change).

...these are all things that I should really document.

Also, just a disclaimer: the iOS, Android, and Emscripten backends are basically dead. They're so dead that nobody even reports bugs for them.

**Comment by torkleyy** [comment]
> Also, just a disclaimer: the iOS, Android, and Emscripten backends are basically dead. They're so dead that nobody even reports bugs for them.

:( That sounds bad.

**Comment by Xaeroxe** [comment]
@francesca64 well you might be getting bug reports for them soon, and likely PRs to fix them too.  Some Amethyst contributors are steering directly into that territory.

**Comment by francesca64** [comment]
@Xaeroxe awesome! I'll do my best to review anything that comes my way.

**Pull request merged**
