### PR TITLE
Remove lifetime from `SimpleState` and `SimpleTrans`

### LINKED ISSUE #1178: Consider using Dispatcher with static lifetime only
There is close to no use case for having a lifetime in a system field, so we should consider exporting the dispatcher with only `'static` as lifetimes. That would also allow us to remove the lifetimes from the state implementations.

### PR DESCRIPTION
**Pull request by torkleyy**
Fixes #1178 

Related: #1152

### CODE REVIEW

**Comment by torkleyy** [comment]
Ah, changelog entry needed.

**Comment by torkleyy** [comment]
Eh, sorry for the merge commit.
bors r+

**Comment by torkleyy** [comment]
Now, one last time:
bors r+

**Comment by jojolepro** [comment]
Gogogo! :)

**Pull request merged**
