### PR TITLE
Maintenance/1711/stabilize code coverage

### PR DESCRIPTION
**Pull request by azriel91**
## Description

Attempt to stabilize code coverage: #1711.

## PR Checklist

By placing an x in the boxes I certify that I have:

- **n/a** Ran `cargo test --all` locally if this modified any rs files.
- **n/a** Ran `cargo +stable fmt --all` locally if this modified any rs files.
- **n/a** Updated the content of the book if this PR would make the book outdated.
- **n/a** Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- **n/a** Added unit tests for new APIs if any were added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

---

Line coverage on `master` has been steady [around 61% to 66%](https://codecov.io/gh/amethyst/amethyst/branch/master)

Stats from successful coverage runs for this branch:

* [85.24%](https://codecov.io/gh/amethyst/amethyst/tree/c8947b8dd7b39e8835d9d736e3b9a2054521d4c6)
* [80.71%](https://codecov.io/gh/amethyst/amethyst/tree/4aed6f93a231740465b46c54891a58b094a751c0)
* [85.11%](https://codecov.io/gh/amethyst/amethyst/tree/eca072d9894cc8c5fc0bce40c896e2f7f3451201)
* [87.45%](https://codecov.io/gh/amethyst/amethyst/tree/8da7714212b3cd3f0d3e8216b865c1557b70910d)
* [87.45%](https://codecov.io/gh/amethyst/amethyst/tree/f6e458086a5b8470bc7e68c3a46429ab363c747e)
* [87.45%](https://codecov.io/gh/amethyst/amethyst/tree/f675b6d5ab0ca94a29036f4a9b14aedb2f05917e)

---

## Build failures:

* Loading shared libraries. Fixed.

    ```
    /home/jenkins/workspace/amethyst_PR-1721@2/target/debug/amethyst_derive-f0acaac7104ce9d6: error while loading shared libraries: libtest-d65243ce23c10440.so: cannot open shared object file: No such file or directory
    ```

* Segmentation fault ([1](https://jenkins.amethyst-engine.org/blue/organizations/jenkins/amethyst/detail/trying/15/pipeline), [2](https://jenkins.amethyst-engine.org/blue/organizations/jenkins/amethyst/detail/PR-1721/11/pipeline)).

    ```
    ./scripts/coverage.sh: line 33: 15752 Segmentation fault      (core dumped) kcov --include-pattern="${crate_dir}/src/,${crate_dir}/tests/" "--exclude-line=${kcov_exclude_line}" "--exclude-region=${kcov_exclude_region}" "${crate_coverage_dir}" "${test_bin_path}"
    script returned exit code 139
    ```

    ```
    ./scripts/coverage.sh: line 37: 32344 Segmentation fault      (core dumped) kcov --include-pattern="${crate_dir}/src/,${crate_dir}/tests/" "--exclude-line=${kcov_exclude_line}" "--exclude-region=${kcov_exclude_region}" "${crate_coverage_dir}" "${test_bin_path}"
    script returned exit code 139
    ```

* Out of disk space.

    ```
    = note: /usr/bin/ld: final link failed: No space left on device
    ```

* Repository failed to clone.

    ```
    Could not lock repository. Please try again
    ```

### CODE REVIEW

**Comment by azriel91** [comment]
yeap! Also, I wanna run this build at least once more after that last push -- the first push I forgot to use the new script 😛.

**Comment by azriel91** [comment]
Hm, I've installed `jq` on the agent, but it isn't detecting it. shall check tomorrow if no one else has.

**Comment by torkleyy** [comment]
see https://github.com/amethyst/builder/pull/3

**Comment by torkleyy** [comment]
bors try

**Comment by torkleyy** [comment]
> LLVM ERROR: IO failure on output stream: No space left on device

**Comment by azriel91** [comment]
Depends on https://github.com/amethyst/builder/pull/4

**Comment by azriel91** [comment]
bors try

**Comment by azriel91** [comment]
```
./scripts/coverage.sh: line 33: 15752 Segmentation fault      (core dumped) kcov --include-pattern="${crate_dir}/src/,${crate_dir}/tests/" "--exclude-line=${kcov_exclude_line}" "--exclude-region=${kcov_exclude_region}" "${crate_coverage_dir}" "${test_bin_path}"
```

**Comment by azriel91** [comment]
```
/home/jenkins/workspace/amethyst_PR-1721@2/target/debug/amethyst_derive-f0acaac7104ce9d6: error while loading shared libraries: libtest-d65243ce23c10440.so: cannot open shared object file: No such file or directory
```

could be to do with multiple containers running off the same source directory, gotta check

**Comment by azriel91** [comment]
bors try

**Comment by azriel91** [comment]
```
+ cargo check --all --all-targets
$ docker top eee0fc522bdd008f3938a992be873acb0e3e848d799bc85d64aab0085a957a46 -eo pid,comm
...
error: You must specify at least one graphical backend feature: "metal" , "vulkan" , "empty"

error: Could not compile `amethyst_rendy`.
```

weird. This is meant to be the Windows job, but that command isn't what's in Jenkinsfile.

**Comment by azriel91** [comment]
https://github.com/bazelbuild/rules_rust/issues/183 appears to be the same symptom.

**Comment by azriel91** [comment]
woo, coverage 85%: https://codecov.io/gh/amethyst/amethyst/tree/c8947b8dd7b39e8835d9d736e3b9a2054521d4c6

build failure was this:
```
  = note: /usr/bin/ld: final link failed: No space left on device
```

**Comment by azriel91** [comment]
Something's filling up disk space that isn't cleaned when cleaning PR dirs.

Before:

```
/dev/md3        412G  390G  262M 100% /
```

After:

```
/dev/md3        412G  308G   83G  79% /
```

It used to clean a lot more.

**Comment by azriel91** [comment]
bors try

**Comment by azriel91** [comment]
```
Could not lock repository. Please try again
```

**Comment by azriel91** [comment]
bors try

**Comment by azriel91** [comment]
Out of 6 good<sup>1</sup> runs, 4 show increased coverage (average 64% changed to average 85%).

I'm confident in calling this ready to merge. @torkleyy @Frizi @fhaynes any objections? There are those 2 segfaults, but I haven't investigated. We can run the build more times in case it's related to the Linux builds happening in parallel (rebased recently for them to be serial).

bors try

---

<sup>1</sup> Loading shared libraries, repository lock contention are solved in code, disk space issue is not related to this PR.

**Comment by azriel91** [comment]
bors try

**Comment by Frizi** [comment]
@azriel91 Is this ready to be merged?

**Comment by azriel91** [comment]
yeaps, was letting it sit in case others had objections. shall merge now

bors r=torkleyy,Frizi

**Pull request merged**
