### PR TITLE
[rs] 03: Moving transform components to core

### PR DESCRIPTION
**Pull request by Rhuagh**

### CODE REVIEW

**Comment by torkleyy** [comment]
So I presume you are going to remove the type param form the passes in a follow-up?

**Comment by Rhuagh** [comment]
Yes. I'm gonna move things to the renderer first though, and remove both the ambient color and transform from passes type parameters.

**Comment by torkleyy** [comment]
It seems you're doing all the restructuring that I planned to do^^

**Comment by Rhuagh** [comment]
Hehe, sorry, you can do it if you want :)

**Comment by torkleyy** [comment]
No it's all good^^

**Comment by Xaeroxe** [comment]
Hey @Aceeri you forgot to use bors

**Comment by Aceeri** [comment]
Oh whoops, forgot we used that here as well now.

**Pull request merged**
