### PR TITLE
[Review] UI Layouts

### PR DESCRIPTION
**Pull request by jojolepro**
Adds layouting systems.
Anchor based layouting: You define which anchor you want, that what offset in pixel you want from there.
e.g TopRight + x: 100, y: 75

Stretching: Stretch the size of a UiTransform to the size of his parents on one or two axes. Uses the screen size if no parent is available.

Stretch margins: Creates space on the sides of something stretched.

See examples/ui for a usage example.

Also, fixes text not being visible if the z isn't between [-1,1]. (Thanks @Xaeroxe )

Once the review process is done, I'll squash the commits.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/591)

### CODE REVIEW

**Comment by jojolepro** [comment]
@AlisCode Proposed to integrate the percent scale mode.
e.g 0.05 width = 5% of screen width.

You can review this PR, but don't merge it. Thanks!

**Comment by jojolepro** [comment]
Except if we find a last minute bug, this is ready for one more review then merge. Be sure to test it yourself to make sure there's no weird corner cases I might have forgot to test. Be aware that a UiText is always aligned at the top left of his UiTransform.

**Comment by torkleyy** [comment]
Reviewed 1 of 7 files at r1, 5 of 6 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[amethyst_ui/src/layout.rs, line 22 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8IgPxRjZTtTE_-DXwC:-L8IgPxRjZTtTE_-DXwD:b-36wxbt) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L22)):*
> ```Rust
> /// Follow a normal english Y,X naming.
> #[derive(Debug, Clone)]
> pub enum Anchor {
> ```

Could we make this a vector maybe? Like `(0.0, 0.0)` is the bottom left, `(0.5, 1.0)` top middle, etc.

---

*[amethyst_ui/src/layout.rs, line 119 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8IhRFohsDZ2tdggFYX:-L8IhRFohsDZ2tdggFYY:bqk3nfo) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L119)):*
> ```Rust
> 
>     /// Adds a margin (spacing) on one or multiple axes.
>     pub fn with_margin(mut self, x: f32, y: f32) -> Self {
> ```

Add to constructor? I think it's annoying to call extra methods here.

---

*[amethyst_ui/src/transform.rs, line 36 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8Iium9jjg_dZAROZ2h:-L8Iium9jjg_dZAROZ2i:b8pps82) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/transform.rs#L36)):*
> ```Rust
>     pub calculated_y: f32,
>     /// Calculated z position by the `UiParentSystem` and `UiLayoutSystem`.
>     pub calculated_z: f32,
> ```

Do we want / need this? Should this be `global_x` and `local_x` maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/591)*

**Comment by Rhuagh** [comment]
Reviewed 1 of 7 files at r1, 4 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[amethyst_ui/src/layout.rs, line 22 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8IgPxRjZTtTE_-DXwC:-L8OUvpWMhvd8ynXHGKS:b-p3hfhl) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L22)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Could we make this a vector maybe? Like `(0.0, 0.0)` is the bottom left, `(0.5, 1.0)` top middle, etc.
</blockquote></details>

The issue with that scheme is that it's not immediately apparent if `0.0` is top, bottom, left or right. I could go either way on this one. 

---

*[amethyst_ui/src/layout.rs, line 119 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8IhRFohsDZ2tdggFYX:-L8OVXIrAkIDem6rYyiX:bql9g86) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L119)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Add to constructor? I think it's annoying to call extra methods here.
</blockquote></details>

Personally, I'd prefer the function and not expand the constructor too much. But again, I could go either way here.

---

*[amethyst_ui/src/layout.rs, line 150 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8OX1cPWCTLsJoKoSAf:-L8OX1cPWCTLsJoKoSAg:biq3758) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L150)):*
> ```Rust
>     fn run(&mut self, (entities, mut transform, mut anchor, parent, screen_dim): Self::SystemData) {
>         for (entity, mut tr, mut anchor) in (&*entities, &mut transform, &mut anchor).join() {
>             if anchor.offset.is_none() {
> ```

This will only work if the viewport is never resized, I think ?

---

*[amethyst_ui/src/layout.rs, line 163 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8OXvz7J4mxlHdK2Kd4:-L8OXvz7J4mxlHdK2Kd5:b-uwcsyx) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L163)):*
> ```Rust
>                 let middle = (screen_dim.width() / 2.0, screen_dim.height() / 2.0);
> 
>                 let new_pos_x = middle.0 + norm_offset.0 * screen_dim.width() + user_offset.0;
> ```

This only works for anchoring in the viewport, not on a parent ?

---

*[amethyst_ui/src/layout.rs, line 389 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8OWjnnTGk8-Y-lHE-x:-L8OWjnnTGk8-Y-lHE-y:b3th94v) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L389)):*
> ```Rust
> 
>         // When you don't have a parent but do have stretch on, resize with screen size.
>         for (entity, mut local) in (&*entities, &mut locals).join() {
> ```

I believe you can add &stretch to the join here, and not do stretch.get() below, to get a smaller result set from the join. The logic should be the same, just an inversion of the fetch.

---

*[amethyst_ui/src/transform.rs, line 36 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8Iium9jjg_dZAROZ2h:-L8OYMmmnukjoMg2Jbh5:b-mfekhx) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/transform.rs#L36)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Do we want / need this? Should this be `global_x` and `local_x` maybe?
</blockquote></details>

I'm in favor of those names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/591)*

**Comment by Rhuagh** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[amethyst_ui/src/layout.rs, line 163 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8OXvz7J4mxlHdK2Kd4:-L8OZ-_TfVWES_vbs1ms:bh1ypi) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L163)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

This only works for anchoring in the viewport, not on a parent ?
</blockquote></details>

Ah, that's handled in the other system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/591)*

**Comment by Rhuagh** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/591)*

**Comment by torkleyy** [comment]
Reviewed 1 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[amethyst_ui/src/layout.rs, line 22 at r4](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8IgPxRjZTtTE_-DXwC:-L8Rw8cPCRp2FpRGxYb3:b-mmtiyv) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L22)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

The issue with that scheme is that it's not immediately apparent if `0.0` is top, bottom, left or right. I could go either way on this one. 
</blockquote></details>

Later on the enum gets transformed into coords anyway.

---

*[amethyst_ui/src/layout.rs, line 119 at r4](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8IhRFohsDZ2tdggFYX:-L8RwIseE2B82-tCxTAk:b4t1xie) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L119)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Personally, I'd prefer the function and not expand the constructor too much. But again, I could go either way here.
</blockquote></details>

It' just that I think we want a margin rather often, so you have to call this method almost always.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/591)*

**Comment by jojolepro** [comment]
Review status: 3 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[amethyst_ui/src/layout.rs, line 22 at r4](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8IgPxRjZTtTE_-DXwC:-L8SJOm6ESlwvMd6sFpq:bjjahvj) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L22)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Later on the enum gets transformed into coords anyway.
</blockquote></details>

I prefer the way it is because its really obvious as to where the anchor is.

---

*[amethyst_ui/src/layout.rs, line 119 at r4](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8IhRFohsDZ2tdggFYX:-L8SJYtaEsoc-RP-j8bX:b-mia5al) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L119)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

It' just that I think we want a margin rather often, so you have to call this method almost always.
</blockquote></details>

I personally use margins minimally. I prefer using pixel size and positioning than margins.

---

*[amethyst_ui/src/layout.rs, line 150 at r4](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8OX1cPWCTLsJoKoSAf:-L8SVSqq0iObUBuHjwC6:b-j6qqbh) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L150)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

This will only work if the viewport is never resized, I think ?
</blockquote></details>

Fixed, thanks a lot!

---

*[amethyst_ui/src/layout.rs, line 163 at r4](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8OXvz7J4mxlHdK2Kd4:-L8SJxnt9ec_WG5rGB80:b-896fix) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L163)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Ah, that's handled in the other system.
</blockquote></details>

Done.

---

*[amethyst_ui/src/layout.rs, line 389 at r4](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8OWjnnTGk8-Y-lHE-x:-L8SLjkv7oxwI45rm_nc:bey5h15) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L389)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

I believe you can add &stretch to the join here, and not do stretch.get() below, to get a smaller result set from the join. The logic should be the same, just an inversion of the fetch.
</blockquote></details>

This happened because there was an else clause before that got removed I think. Done.

---

*[amethyst_ui/src/transform.rs, line 36 at r4](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8Iium9jjg_dZAROZ2h:-L8SSyH56IbziwEXEQb0:b-896fix) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/transform.rs#L36)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

I'm in favor of those names.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/591)*

**Comment by torkleyy** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[amethyst_ui/src/layout.rs, line 119 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8IhRFohsDZ2tdggFYX:-L8S_uzkyBtzg2xfCaOi:b-i3u60o) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L119)):*
<details><summary><i>Previously, jojolepro (Joël Lupien) wrote…</i></summary><blockquote>

I personally use margins minimally. I prefer using pixel size and positioning than margins.
</blockquote></details>

I still think it belongs to the constructor since there won't be many more things to add here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/591)*

**Comment by jojolepro** [comment]
https://github.com/amethyst/amethyst/pull/601
The ui code contains a duplicate of the transform system, and thus contains the same bugfix.
The performance optimisation requested in that PR's reviews can't be applied before the new version of specs is released, because I can't go from an entity id back to the entity in without looking through all of them (yet). 
I suggest we merge this when everyone is happy with it, and I modify the #601 PR when the new specs is available to optimise both parenting codes.

**Comment by jojolepro** [comment]
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[amethyst_ui/src/layout.rs, line 119 at r4](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8IhRFohsDZ2tdggFYX:-L8Se3FD4lhIRMKqaVi8:b-896fix) ([raw file](https://github.com/amethyst/amethyst/blob/47e3bda5abbe58697bc633ed1864be9d9282e8b0/amethyst_ui/src/layout.rs#L119)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

I still think it belongs to the constructor since there won't be many more things to add here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/591)*

**Comment by torkleyy** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/591#-:-L8SgDzLimksegFNyPDl:bnfp4nl)*

**Comment by Rhuagh** [comment]
Reviewed 3 of 5 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[amethyst_ui/src/layout.rs, line 111 at r6](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8TeZUiLDgRpEKnuwAQ:-L8TeZUiLDgRpEKnuwAR:bwbxbfo) ([raw file](https://github.com/amethyst/amethyst/blob/46bcdbcf2ccf7910e1c0b0b0398d1eb555537070/amethyst_ui/src/layout.rs#L111)):*
> ```Rust
> impl Stretched {
>     /// Create a new `Stretched` component using the `Stretch` setting.
>     pub fn new(stretch: Stretch,margin_x: f32,margin_y: f32) -> Self {
> ```

Formatting.

---

*[amethyst_ui/src/layout.rs, line 124 at r6](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8TedheVXkc6NcHZRrX:-L8TedheVXkc6NcHZRrY:besgyfe) ([raw file](https://github.com/amethyst/amethyst/blob/46bcdbcf2ccf7910e1c0b0b0398d1eb555537070/amethyst_ui/src/layout.rs#L124)):*
> ```Rust
> 
> /// Used to initialize the `UiTransform` and `Anchored` offsets when using the `Anchored` component.
> pub struct UiLayoutSystem{
> ```

Formatting

---

*[amethyst_ui/src/layout.rs, line 133 at r6](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8Teg0viKqPMDvb3ucM:-L8Teg0viKqPMDvb3ucN:besgyfe) ([raw file](https://github.com/amethyst/amethyst/blob/46bcdbcf2ccf7910e1c0b0b0398d1eb555537070/amethyst_ui/src/layout.rs#L133)):*
> ```Rust
>         UiLayoutSystem {
>             screen_size: (0.0,0.0),
>         }
> ```

Formatting

---

*[amethyst_ui/src/text.rs, line 358 at r6](https://reviewable.io:443/reviews/amethyst/amethyst/591#-L8TfBaEHWOilRf9RE4B:-L8TfBaEHWOilRf9RE4C:bwerwus) ([raw file](https://github.com/amethyst/amethyst/blob/46bcdbcf2ccf7910e1c0b0b0398d1eb555537070/amethyst_ui/src/text.rs#L358)):*
> ```Rust
>                                 .join()
>                                 .filter(|&(_, t)| {
>                                     t.local_x <= self.mouse_position.0
> ```

Should this really be the local coordinates, is the mouse position also described in local coordinates?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/591)*

**Comment by jojolepro** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[amethyst_ui/src/layout.rs, line 111 at r6](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8TeZUiLDgRpEKnuwAQ:-L8U15S382AwwrDpy_YU:b-896fix) ([raw file](https://github.com/amethyst/amethyst/blob/46bcdbcf2ccf7910e1c0b0b0398d1eb555537070/amethyst_ui/src/layout.rs#L111)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Formatting.
</blockquote></details>

Done.

---

*[amethyst_ui/src/layout.rs, line 124 at r6](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8TedheVXkc6NcHZRrX:-L8U15g-0CBPyRQqWq9J:b-896fix) ([raw file](https://github.com/amethyst/amethyst/blob/46bcdbcf2ccf7910e1c0b0b0398d1eb555537070/amethyst_ui/src/layout.rs#L124)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Formatting
</blockquote></details>

Done.

---

*[amethyst_ui/src/layout.rs, line 133 at r6](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8Teg0viKqPMDvb3ucM:-L8U16SXBd4NTZJPS17g:b-896fix) ([raw file](https://github.com/amethyst/amethyst/blob/46bcdbcf2ccf7910e1c0b0b0398d1eb555537070/amethyst_ui/src/layout.rs#L133)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Formatting
</blockquote></details>

Done.

---

*[amethyst_ui/src/text.rs, line 358 at r6](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-L8TfBaEHWOilRf9RE4B:-L8U171QE5FaMX5ZvrJk:b-5crhuj) ([raw file](https://github.com/amethyst/amethyst/blob/46bcdbcf2ccf7910e1c0b0b0398d1eb555537070/amethyst_ui/src/text.rs#L358)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Should this really be the local coordinates, is the mouse position also described in local coordinates?
</blockquote></details>

Done. Thanks for that!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/591)*

**Comment by torkleyy** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r7.
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-:-L8Va54pEQgNDT0Qf1N-:bnfp4nl)*

**Comment by torkleyy** [comment]
Reviewed 2 of 3 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/591)*

**Comment by jojolepro** [comment]
I just realized that changing transform.x to transform.local_x broke all projects using ui...

**Comment by Rhuagh** [comment]
Don't be afraid of doing breaking changes to unreleased code.

**Comment by jojolepro** [comment]
I meant I didn't update the examples :D pong doesn't compile

**Comment by Rhuagh** [comment]
Yeah, I noticed

**Comment by jojolepro** [comment]
Fixed @Rhuagh

**Comment by Rhuagh** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/591#-:-L8htCu-0g7qqlgT7--G:bnfp4nl)*

**Comment by Rhuagh** [comment]
bors r=torkleyy,Rhuagh

**Comment by jojolepro** [comment]
Anyone on mac can test and report if the text is inside or outside the top button?
cargo run --example ui

**Pull request merged**
