### PR TITLE
Add correct path to large files in examples

### PR DESCRIPTION
**Pull request by Blisto91**
## Description

The ``.gitattributes`` file wasn't looking in the correct path for the LFS files after the assets were moved into their respective example folders.

I noticed that not all large files are in a folder named large, like ``teapot.obj`` in ``arc_ball_camera``, so it now includes all the files as long as they are in the assets folder.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Updated the content of the book if this PR would make the book outdated.

### CODE REVIEW

**Comment by 0x6273** [comment]
> I noticed that not all large files are in a folder named large, like teapot.obj in arc_ball_camera, so it now includes all the files as long as they are in the assets folder.

That would put smaller files, like the assets for the pong tutorial, into lfs as well. I think we only want the exemples with very large assets to require installing the extension.

**Comment by Blisto91** [comment]
@Blisto91 Ah rgr. Git newbie here! 😁
I guess it should only point to the large assets folder then.

When is a file large enough that it must be tracked with lfs?
``scene.bin`` in ``examples\rendy\assets\large\crystal_stone\`` is only 20KB
While ``teapot.obj`` in  ``examples\arc_ball_camera\assets\mesh\`` is 7.24MB

**Comment by Blisto91** [comment]
I'll squash before merge but i guess this is more correct now.

**Review by jojolepro — APPROVED** [review]

**Pull request merged**
