### PR TITLE
Updated: env_logger, gfx

### PR DESCRIPTION
**Pull request by TimonPost**
## Description

Updated `env_logger` and `base64`.
## PR Checklist

By placing an x in the boxes I certify that I have:

- [ X ] Ran `cargo test --all` locally if this modified any rs files.
- [ X ] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [ X ] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by jojolepro** [comment]
I don't see gfx updated, only env_logger and base64?

**Comment by TimonPost** [comment]
Sorry, my bad.

**Comment by jojolepro** [comment]
So... it was intended or not? :P

You can merge if it was :)

**Comment by fhaynes** [comment]
@TimonPost please either merge this or close it

**Comment by TimonPost** [comment]
bors +r

**Pull request merged**
