### PR TITLE
[FEATURE] Custom Logger Formatter

### PR DESCRIPTION
**Pull request by nalshihabi**
Implements #1889 

## Description

Add a custom log formatter option to the Amethyst logger so that instead of setting up their own logger to use their own formatting, a developer using Amethyst can just pass in their own formatter to the Amethyst logger.

## Additions

- `Logger::new_formatter`: a different constructor for Amethyst logger where a custom formatter can be passed as a parameter.
- `Logger::from_config_formatter`: a different function for the Logger for starting a new Logger with a config and a formatter.
- `Logger::new_with_config`: helper function that much of the functionality of `Logger::from_config` was moved into from `Logger::from_config` in order to allow for the functionality to be reused easily by `Logger::from_config_formatter`.

## Removals

None

## Modifications

- `Logger::from_config`: Changed to just call `Logger::from_config_formatter` with valid parameters for the helper function.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [ ] Updated the content of the book if this PR would make the book outdated.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by azriel91** [comment]
file system race condition:

```
Could not lock repository. Please try again
```

bors try

**Comment by nalshihabi** [comment]
For the file system race condition, what might need to be done about it?

**Comment by azriel91** [comment]
Not sure yet (maybe run the jobs serially) -- initially I thought it was duplicated work (as in, no value running across `nightly` and `stable`), but then there was once a bug was caught in stable but not on nightly.

Shall fix it when i'm more awake.

bors r=azriel91,distransient

**Comment by azriel91** [comment]
bors r=azriel91,distransient

**Pull request merged**
