### PR TITLE
Update examples/README.md

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
## Description
In the `examples/README.md` file it was specified to use a backend:
```markdown
and `$BACKEND` is your graphics backend (u....
```
but was not actually used in the command used to run the examples.

## Checklist:
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by grzi** [comment]
Hey, actually the goal is the opposite. We removed the need to set the backend in the commands.

**Comment by Andy-Python-Programmer** [comment]
> Hey, actually the goal is the opposite. We removed the need to set the backend in the commands.

So should I remove the $BACKEND part?

**Comment by grzi** [comment]
@Andy-Python-Programmer It needs to be removed. 

Moreover, can you check the strict-book branch for doc PR ? @ezpuzz has already started to update to book, we'll keep its branch for this.

**Review by grzi — APPROVED** [review]

**Comment by Andy-Python-Programmer** [comment]
Hmm what happened.

**Comment by Andy-Python-Programmer** [comment]
Let me make the pr again.

**Pull request closed without merging**
