### PR TITLE
Book copy-editing and minor revision

### PR DESCRIPTION
**Pull request by gardrek**
Fix section "Getting Started"
Minor typing errors and a change to the introduction to be accurate.

### CODE REVIEW

**Comment by LucioFranco** [comment]
If yo need help with squashing just ping me on discord 😄

**Comment by LucioFranco** [comment]
bors r=Jojolepro, Luciofranco

**Comment by jojolepro** [comment]
Thanks

**Comment by jojolepro** [comment]
I had accidentally cancelled bors, but its just doc changes

**Pull request merged**
