### PR TITLE
Fix forward renderer on more strict graphics drivers such as Intel Mesa

### PR DESCRIPTION
**Pull request by palodequeso**
I just chose some names for the in and out structures, but if we want to change them, or develop a standard, we should do it now.

### CODE REVIEW

**Comment by kvark** [comment]
I don't think it makes sense to keep `v_` prefixes for stuff inside your interface structs.

**Comment by palodequeso** [comment]
> I don't think it makes sense to keep v_ prefixes for stuff inside your interface structs.

I struggled with that, and landed on shooting in the dark. but we can't just use ```in``` and ```out``` because those are reserved... suggestions?

**Comment by kvark** [comment]
No, I mean for stuff **inside** the structs, like `v_In.position` instead of `v_In.v_Position`.

**Comment by palodequeso** [comment]
That should do it.

**Pull request merged**
