### PR TITLE
#88. Remove String from Asset Manager.

### PR DESCRIPTION
**Pull request by bjadamson**
Here's an example of what I'm thinking, I've simply replaced the String types with integer wrappers.

I'm guessing there are quite a few problems with the pull request as is, but I'd love feedback on this line of changes.

### CODE REVIEW

**Comment by kvark** [comment]
I'd rather find a way to avoid `str -> String` conversion on lookups (while still storing String) than moving to pure IDs.

**Comment by Emilgardis** [comment]
@kvark a small change would be 

    fn get_mesh<T: Into<String>>(mesh: T)

That way the user chooses if a conversion is done.

**Comment by kvark** [comment]
Maybe 'T: Borrow<&str> + Hash'?

**Comment by kvark** [comment]
This approach wouldn't get rid of `String` conversions:
```rust
fn get_mesh<T: Into<String>>(mesh: T)
```
In the best case, it would be equivalent to `clone()` but still be allocating...

**Comment by nchashch** [comment]
Maybe instead of taking ID's as arguments return them? Like:
```rust
    fn load_texture(&mut self, texture_data: TextureData) -> Option<TextureID> {
        ...
    }
```
Then `Vec`s can be used to store assets instead of `HashMap`s.
It probably wouldn't introduce much inconvenience, for example instead of writing:
```rust
context.asset_manager.create_constant_texture("dark_blue", [0.0, 0.0, 0.01, 1.]);
context.asset_manager.create_constant_texture("green", [0.0, 1.0, 0.0, 1.]);
context.asset_manager.gen_sphere("sphere", 32, 32);

let fragment = context.asset_manager.get_fragment("sphere", "dark_blue", "green", transform).unwrap();

```
you would write:
```rust
let dark_blue = context.asset_manager.create_constant_texture([0.0, 0.0, 0.01, 1.]).unwrap();
let green = context.asset_manager.create_constant_texture([0.0, 1.0, 0.0, 1.]).unwrap();
let sphere = context.asset_manager.gen_sphere(32, 32).unwrap();

let fragment = context.asset_manager.get_fragment(sphere, dark_blue, green, transform).unwrap();
```
IDs are type checked, so you can't query a `Texture` with a `MeshID`, and instead of failing silently asset manager returns `None` if the asset can't be loaded.

Although there is still a problem with "asset leaks" when an ID has gone out of scope and the user didn't free the asset.

**Comment by bjadamson** [comment]
I think suggestion from @nchashch makes sense to me, but it's basically the same thing as using integer wrappers (handles). This is what OpenGL does.

> I'd rather find a way to avoid str -> String conversion on lookups (while still storing String) than moving to pure IDs. @kvark 

Why store a String? Would an abstraction that stores a String built on-top of this asset manager be equivalent for your uses?

**Comment by Aceeri** [comment]
@bjadamson Are you still interested in this?

**Comment by ebkalderon** [comment]
@bjadamson Hey, are you still working on this? This PR is getting quite stale. If no one is willing to pick it up and finish, we may have to close it.

**Comment by ebkalderon** [comment]
Given that the companion issue #88 has been closed, I will close this PR as well.

**Pull request closed without merging**
