### PR TITLE
Bumping Winit to 0.10 and various Gfx libraries to latest

### PR DESCRIPTION
**Pull request by Hittherhod**
A few changes shook out of this; primarily `MouseMoved` becoming `CursorMoved` and `get_primary_monitor` becoming an instance method of an `EventsLoop`. I also had to bump some gfx libraries so I didn't get version conflicts.

One caveat that I was sure how to solve (because I can't tell if it's even used):
Because `get_primary_monitor()` became associated with `EventsLoop`, it makes `From<DisplayConfig> for WindowBuilder` a bit odd. `WindowBuilder` doesn't know anything about an EventsLoop, but for the fullscreen option it needs a monitor. I just made a temporary `EventsLoop` and called that temporary's `get_primary_monitor()`, which isn't the best but I couldn't think of another way to do it. I couldn't find an example in the repo of utilizing this trait so I didn't know what alternatives might exist.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/539)

### CODE REVIEW

**Comment by torkleyy** [comment]
Only concern I have is whether it is allowed to have multiple `EvenLoop`s.

**Comment by Hittherhod** [comment]
I updated the rustfmt.toml file to use newer options (things like the attributes_same_line were no longer valid so it was just using the default). I also changed the `From<DisplayConfig> for WindowBuilder` to just be `DisplayConfig::to_windowbuilder()` and accept an event loop. Please forgive the commit history. Something janky happened when I updated rustfmt.toml

**Comment by Rhuagh** [comment]
Make sure to rebase onto develop

---

Reviewed 1 of 60 files at r4.
Review status: 1 of 60 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/539#-:-L2ulC-VlXTSoeds6i0O:b-nbxyac)*

**Comment by Hittherhod** [comment]
I thought I had, but I'm not sure. I think develop got pushed while making my last batch of changes, so things might have gotten weird then

---

Review status: 1 of 60 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/539#-:-L2uxyOXM6eCKESK0sYL:b-tj9awb)*

**Comment by Rhuagh** [comment]
Pretty sure you're missing the formatting fixes

**Comment by Hittherhod** [comment]
Check if it's fixed now. It's super confusing though, because I do a rebase on upstream/develop, then have to do a pull, then merge those changes again, then I can push. It's super confusing.

---

Review status: 1 of 60 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/539#-:-L2vEPAq0OtdkJ4lTCS1:b2m5dh9)*

**Comment by torkleyy** [comment]
I think you should read a guide for git. After the rebase, you need to do a force push (git push -f origin branch).

**Comment by Rhuagh** [comment]
rebase rewrites the history, so after a rebase you should expect to see something about the branch upstream and your local branch differs, at that point you want to do git push -f.

**Comment by Hittherhod** [comment]
Okay. I just did a git push -f origin feature/bump_winit, so I think the
changes should be fine.

**Comment by omni-viral** [comment]
Thank you!
bors r+

**Pull request merged**
