### PR TITLE
Add raw mouse events and format

### PR DESCRIPTION
**Pull request by Xaeroxe**
Note to reviewers: The only part with any meaningful changes is the amethyst_input files.  Everything else is formatting.

This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/699)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
0.3.8-nightly (346238f4 2018-02-04)

**Comment by MrMinimal** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/699)*

**Comment by jojolepro** [comment]
I wonder if my graphics tablet would generate mouse moved events :thinking:

**Comment by Xaeroxe** [comment]
You should try it!

**Comment by jojolepro** [comment]
doing that right now :P

**Comment by MrMinimal** [comment]
@jojolepro I just tried my Wacom on Linux X11 and it does produce events, but every delta is in the thousands even if I don't move. The mouse's delta is between -10 and +10.

**Comment by Xaeroxe** [comment]
@MrMinimal haha, that's bizarre.  I hope gamers don't have these tablets plugged in while they're playing I guess

**Comment by Rhuagh** [comment]
Device events will generally be quite different from device to device, it's one of the drawbacks of using the raw data. We should consider how to add scaling factors to different device types.

**Comment by jojolepro** [comment]
I assume most games would want to have adjustments for that. Something like "put your pen in the bottom left, now in the top right" and it calculates the sensitivity accordingly. I have yet to find a 3d game made for mouse players that supports tablets at all (without needing the tablet driver to have a mouse emulation mode). Usually you want to use tablets for their absolute position input anyway.

A quick fix would be to let user set a custom sensitivity of 0.001 in the game's setting files.

**Comment by MrMinimal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/699)*

**Comment by jojolepro** [comment]
One more review from anyone = merge

**Pull request merged**
