### PR TITLE
Locking khronos_api at 1.0.1 because 1.1.0 is broken

### PR DESCRIPTION
**Pull request by Rhuagh**
This issue also exists in master and our released version, so this is for fixing those.
Note we need to release a patch version after this has been merged into master.

### CODE REVIEW

**Comment by Xaeroxe** [comment]
bors r+

I am unable to publish myself, I hope someone else can.

**Comment by Rhuagh** [comment]
Everyone in engine-devs should be able to.

**Comment by torkleyy** [comment]
@Rhuahh as far as I know you should have an invite to the Amethyst org.

**Comment by Xaeroxe** [comment]
Overriding

**Pull request merged**
