### PR TITLE
Allow disabling parallel support in amethyst_core (for WASM support)

### PR DESCRIPTION
**Pull request by AThilenius**
Hi all. This is both an intro and a tiny patch.

## Background / Intro

I'm using Amethyst (right now only `amethyst_core`) for a browser-based game written in Typescript and Rust. Along with `stdweb` it feels like a match made in heaven, and every day I'm more impressed by both Rust and Amethyst-spawned crates. 😍 Rendering is shelled out to `THREE.js` for now, until `wgpu-rs` or Amethyst are ready for WASM prime-time. Anyway, I figured I would hijack this PR to say hello 👋 and **inquire as to the WASM plan/timeline for Amethyst**. For example, Amethyst (including `core`) pulls in `rayon` directly but treading support isn't there just yet. I'm happy to help anywhere work overlaps! I'll need a few bleeding-edge things like a half decent UDP stack (so `WebRTC`). Would rather my efforts went to something shared than a private code base, if that's ever possible.

You're all awesome, keep up the great work 🍻

## Description
Threading support isn't there yet for browsers, and causes a panic when you try to use a `shred::DispatcherBuilder`:
_`backend.js:1 Panic error message: Invalid configuration: ThreadPoolBuildError { kind: IOError(Custom { kind: Other, error: "operation not supported on wasm yet" }) }`_

This PR continues piping the ability to disable parallel support in `shred` up through `amethyst_core` so that WASM consumers (like me) can disable it.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by AThilenius** [comment]
The coverage report looks like a false positive?

**Comment by jojolepro** [comment]
Multithreading is supported by wasm. See this crate: https://github.com/jojolepro/web_worker

For an example on how it is used, see this example: https://github.com/jojolepro/specs_wasm

**Comment by AThilenius** [comment]
Thank you @jojolepro, that's an awesome reference to have, and I'm super excited about the future of WASM and Rust! :) So cool to see all the effort behind this, and the potential of it. After a decade of JS, threading in a browser from a systems level language seems like a dream. It's surreal to see all this crazy powerful tech actually becoming a thing.

Unfortunately in my case with WASM, Firefox-nightly + a user-set flag isn't considered supported, it's hard to require early testers go to that much effort to load a URL. This PR doesn't change any default behaviors, it just allows a consumer of `amethyst_core` to disable parallel support. In my case, it would be disabled until Chrome stable has been shipping with shared buffers enabled for a few months :( But the future is bright!

**Comment by jaynus** [comment]
I have one concern about this. What happens if we begin using par_iter in the engine internals? Does it shim for not-actually-threaded? I believe the build would fail. This means we need to feature gate all future usage of it.

**Comment by distransient** [comment]
I believe this should be only a shim for now, and we shouldn't worry too much about "if this in the future". Jojo's solution should be the actual proper way going forward.

**Comment by jaynus** [comment]
Bors r+

**Comment by jaynus** [comment]
bors retry

**Pull request merged**
