### PR TITLE
Rename transforms

### PR DESCRIPTION
**Pull request by Xaeroxe**
This PR does nothing but rename

- `Transform` -> `GlobalTransform`
- `LocalTransform` -> `Transform`

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/563)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
#558 merged, this PR has been rebased.  I'd like to merge this ASAP to reduce conflict pain.

r? @Rhuagh @Aceeri

**Comment by Xaeroxe** [comment]
Also added in the last rebase:

`LocalTransformChannel` -> `TransformChannel`

**Comment by Rhuagh** [comment]
Reviewed 46 of 46 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[amethyst_animation/src/systems/control.rs, line 107 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/563#-L4wBogUGUi8yLE5agcw:-L4wBogUGUi8yLE5agcx:bcibhtt) ([raw file](https://github.com/amethyst/amethyst/blob/010997b8455bce33676f29dbd36e94c3a3b4c08b/amethyst_animation/src/systems/control.rs#L107)):*
> ```Rust
> /// - `sampler_storage`: `AssetStorage` for all `Sampler`s
> /// - `samplers`: the active sampler sets
> /// - `transforms`: `LocalTransform`s, used to retrieve the rest pose before animation starts.
> ```

This is incorrect documentation, but I'll fix that in a followup PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/563)*

**Pull request merged**
