### PR TITLE
Refine the steps

### PR DESCRIPTION
**Pull request by CleanCut**
## Description

Update the steps a bit with what I learned in the 0.15.2 release

### CODE REVIEW

**Review by TimonPost — APPROVED** [review]

**Comment by Blisto91** [comment]
I understand why git prefers wording _Fix_ instead of _Fixed_ when writing commit messages, but i expect a public facing Changelog to list what have been _Fixed_.
So this commit will Fix X, Y & Z if merged and when it finally has been merged the user can read in the changelog that we have Fixed X, Y & Z

**Comment by CleanCut** [comment]
@Blisto91 Ya, I was just mirroring Git conventions. We can switch it over to past tense if it makes more sense for the changelog.

**Comment by Blisto91** [comment]
Don't feel strongly about either. So what you think is fine 👍

**Review by Blisto91 — APPROVED** [review]

**Comment by Blisto91** [comment]
Looks like rendy fails to build on the latest nightly.
Confirmed on my own pc.

**Comment by CleanCut** [comment]
Created an issue upstream for the nightly compile errors: https://github.com/rust-lang/rust/issues/76428

**Pull request merged**
