### PR TITLE
Doc/0 13 0 release notes

### PR DESCRIPTION
**Pull request by azriel91**
## Description

Migration notes for 0.13. Mostly:

* `specs` upgrade
* `SystemDesc` trait

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- **n/a** Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
-  **n/a** Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by azriel91** [comment]
bors try

**Comment by distransient** [comment]
Gonna try and merge this last so we can add in anything else that gets merged today

**Comment by distransient** [comment]
bors retry

**Pull request merged**
