### PR TITLE
Amethyst 0.8 Release: Push to master

### PR DESCRIPTION
**Pull request by jojolepro**
Merging develop into master

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/843)

### CODE REVIEW

**Comment by jojolepro** [comment]
This is going through bors to ensure the CI is going through.

:pray: for no mistakes.

Enjoy!

bors r+

**Comment by Moxinilian** [comment]
bors retry

**Comment by jojolepro** [comment]
Both CI passed. Then bors crashed, then travis has the wrong permissions and crashed too. Bypassing the checks because I don't want to sit here for the next 20 hours.

**Pull request merged**
