### PR TITLE
Refactored the pong tutorial code

### PR DESCRIPTION
**Pull request by daniel-dietrich**
## Description
I have refactored the pong code and updated the pong tutorial chapters to make them easier to understand. 

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by azriel91** [comment]
Heya, thank you very much for this; haven't yet gotten to reviewing it, but it's very much appreciated :bowing_man:

**Comment by azriel91** [comment]
Heya :wave:, I've only had time to skim, but am happy that the code is organized into smaller modules and the code snippets are updated (thanks :v:!). Most of the code snippets have had the `extern crate amethyst` removed, which happen to be needed because that's how `mdbook` knows it's necessary to link that crate in when testing snippets.

There's some functions that may be renamed (like `reverse_x`, `heads_*`), but that's already much better than the inlined source code.

---

Originally I was going to get this merged, then work on then WASM extension to the tutorial, but I'm short on time (deadline is in a few days) so I'll be writing a "extend this to support WASM" chapter based on the previous code structure.

**Comment by jojolepro** [comment]
Needs a rebase to fix the conflicts!

**Comment by AlveLarsson** [comment]
Is this ready?, we are prepping for 0.15.1 now.

**Pull request closed without merging**
