### PR TITLE
refactor: Update specs

### PR DESCRIPTION
**Pull request by Rhuagh**
Do not merge this before specs has been released. 

WIP

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/606)

### CODE REVIEW

**Comment by Rhuagh** [comment]
The parent systems aren't working yet btw.

**Comment by jojolepro** [comment]
The pr is still opened, though I can't finish it before at least monday.

**Comment by Rhuagh** [comment]
There are atleast four bugs in the current parenting systems, so I'm working on a new generic version

**Comment by jojolepro** [comment]
Theres a bug where the system is doing only one "layer" of parenting at a time. If you have a ui with 3 or more parents one under the other, youll see it takes time for everything to move into the right places.

**Comment by Rhuagh** [comment]
Yeah, I'm currently writing a parenting system that is generalised, outside amethyst (based on @Aceeri's stuff)

**Comment by Rhuagh** [comment]
Closing this one to not waste travis time on my changes until they're ready. Will open a new once I'm nearing completion.

**Pull request closed without merging**
