### PR TITLE
fix: Update winit+glutin+gfx_window_*

### LINKED ISSUE #544: Pong Example Player 1 (Left Hand) ScoreText Does Not Appear
I'm using the Pong Example to learn some of the components of amethyst, but I'm confused as to why the left-side player (player 1)'s score isn't showing up. It has something to do with the coordinate system, which has me confused. The arena is configured to be 100 x 100, which is why I assume the constant "100" appears in pong.rs in the translation closures. However, the first closure evaluates to a negative number (because the ScreenDimensions are 0 at the time the `initialise_paddles()` is called #536). 

I've played around with the numbers, and it seems like the camera projects such that the visible x-coordinate values are 0-1000. I'm not super sure of the math behind it though, so I can't figure out a equation that uses knowledge of arena properly.

### PR DESCRIPTION
**Pull request by Rhuagh**
Fixes #544. 

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/648)

### CODE REVIEW

**Comment by jojolepro** [comment]
I'd like a confirmation from @Hittherhod that this fixes #547

**Comment by Hittherhod** [comment]
@Rhuagh @jojolepro Nope. I'm still seeing issues upon resizing the pong example.
screen shot 2018-04-16 at 20 49 21

**Comment by Rhuagh** [comment]
So it's not fixing that issue then, got it.

**Pull request merged**
