### PR TITLE
Fix Specs book link

### PR DESCRIPTION
**Pull request by torkleyy**
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/518)

### CODE REVIEW

**Comment by Rhuagh** [comment]
Small enough it's not worth waiting.

bors r+

**Comment by Rhuagh** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/518)*

**Comment by Xaeroxe** [comment]
Erroneous failure, retrying.

bors r+

**Comment by torkleyy** [comment]
bors r=Xaeroxe

**Comment by torkleyy** [comment]
bors r=Xaeroxe,Rhuagh

**Comment by Xaeroxe** [comment]
Overriding.

**Pull request merged**
