### PR TITLE
Fix appveyor CI

### PR DESCRIPTION
**Pull request by nchashch**
Changes:
* Add stable and beta channels to appveyor.yml
* Add x86_64-pc-windows-gnu target to appveyor.yml
* Allow failure for nightly channel build for appveyor CI

### CODE REVIEW

**Comment by selaux** [comment]
What about using rustup?
```
-cmd: rustup-init.exe -y --default-toolchain ${env:channel}-${env:target}
```

**Comment by Aceeri** [comment]
I think we might be able to just update gfx to 0.13.0 once it is published since that seems to fix any problems with `use $crate`.

**Comment by Aceeri** [comment]
Solved by updating the dependencies https://github.com/amethyst/amethyst/pull/136.

**Comment by kvark** [comment]
Note: it's a good habit to squash small changes like this. Helps bisection of any problems later on.

**Pull request merged**
