### PR TITLE
fix compilation bug

### PR DESCRIPTION
**Pull request by covercash2**
## Description

fixed a compilation bug with the nightly compiler.

## Modifications

i made it a little more idiomatic and easier to follow, IMO.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Ran `cargo test --all` locally if this modified any rs files.
- [x] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [n/a] Updated the content of the book if this PR would make the book outdated.
- [n/a] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [n/a] Added unit tests for new APIs if any were added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by covercash2** [comment]
it should. using `return` is just personal preference. 

the compiler wasn't able to infer the type for `name.as_ref()`, and since the `load` method takes a `Into<String>` I thought just `clone`ing them would be effectively the same resource-wise. although I s'pose `name.as_ref::<&str>()` could work as well, but it doesn't save an allocation to pass a reference and the other resources are being cloned so I thought that would give a clearer picture of what was happening at the call site (not airtight reasoning, admittedly).

**Comment by azriel91** [comment]
ah, sound enough reasoning for me 💯🥇

**Comment by totorigolo** [comment]
This PR fixes the regression for `0.11`, so projects using earlier versions (and which don't want/cannot migrate) are stuck with Rust **1.35.0**. I personally don't really mind, because I consider [my game](https://github.com/totorigolo/fuite-rs) done, but I wanted to warn about this breakage, because older games will now just **not compile**. Maybe you should consider to backport fix this to older versions.

How-to fix for future readers:
* update to Amethyst 0.11+ (if you are actively developing a game)
* `rustup override set 1.35.0` / `cargo +1.35.0 run` (if you just want to run old games)

**Pull request merged**
