### PR TITLE
[WIP] Amethyst Renderer WASM Support (OpenGL)

### PR DESCRIPTION
**Pull request by omni-viral**
## Description

Adds OpenGL/WebGL support

### CODE REVIEW

**Comment by jojolepro** [comment]
I see that you removed the threadpool in a lot of places. 
However, we do have support for rayon threadpool through the use of this crate https://github.com/jojolepro/web_worker which uses a custom executor based on web workers.

No changes are required inside of amethyst related to the thread pool usage. Only the thread pool creation is different for wasm. :)

**Comment by distransient** [comment]
Hey, @omni-viral what's the state of this? Is it blocked on anything?

**Comment by omni-viral** [comment]
@distransient yes. On `winit` :(

**Comment by CleanCut** [comment]
Does the release of [`winit 0.20.0-alpha4 on 2019-10-18`](https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md#0200-alpha-4-2019-10-18) unblock this?

**Comment by fhaynes** [comment]
> Does the release of [`winit 0.20.0-alpha4 on 2019-10-18`](https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md#0200-alpha-4-2019-10-18) unblock this?

I believe so. @jojolepro can you take a look at this? @omni-viral it would be helpful if you could respond to this.

**Comment by pheki** [comment]
`winit 0.20.0` has been finally released!

**Comment by azriel91** [comment]
@pheki Yeaps! Though there's a new blocker within `winit 0.20.0` :sweat_smile:. See https://github.com/amethyst/amethyst/pull/2040#issuecomment-572238365

**Comment by semtexzv** [comment]
It seems that almost everything is blocked on `cpal` & `winit` not being able to agree on what COM thread apartment to choose. `winit` needs single threaded for drag & drop support and `cpal` needs multi-threaded.

**Comment by azriel91** [comment]
Thanks for the info :v:, shall add some links:

* https://github.com/rust-windowing/winit/issues/1255
* https://github.com/rust-windowing/winit/issues/1185
* https://github.com/RustAudio/cpal/pull/348

**Comment by fhaynes** [comment]
Can we please fork them and make them agree?

**Comment by semtexzv** [comment]
Edit: Another issue is threading. Current master rebased to use rendy 0.5, winit 0.21 & glutin 0.23 crashes when trying to build meshes.

This PR resolved it by just removing threadpool, However, I don't think this is the right idea. Using threads for asset processing is a hard requirement.

We either need to be able to pin specific systems to specific threads and split up the processing to several stages, 

OR provide a way to express a possible dependency on current thread in form of a function accepting closure.

OR resolve it at the level or rendy.

**Comment by azriel91** [comment]
Closing -- best follow the [WASM project](https://github.com/amethyst/amethyst/projects/20), and use the [`wasm` branch](https://github.com/amethyst/amethyst/tree/wasm).

**Comment by pheki** [comment]
@azriel91 note that for OpenGL the issue to follow is (I think) #2097

**Comment by finnbear** [comment]
The issue was address here: https://hg.mozilla.org/mozilla-central/rev/7137d009d9799735a8a7056aefe12eeb732a815d
But the change was reverted hours later: https://hg.mozilla.org/mozilla-central/rev/f4900b660459

**Pull request closed without merging**
