### PR TITLE
Fix README logo path

### PR DESCRIPTION
**Pull request by Moxinilian**
The logo path is broken. This fixes it.
This is my most important pull request so far, and I would like to thank @Xaeroxe, @jojolepro, and all the other people I forgot to mention for their precious help in getting this fix working.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/836)

### CODE REVIEW

**Comment by LucioFranco** [comment]
I would verify you are basing this branch off of develop and not the one that has the cache changes since I also see those changes in here as well.

**Comment by Moxinilian** [comment]
Yeah I derped when I created my readme-path branch. It's fixed now.

**Comment by jojolepro** [comment]
bors r+

I don't think we'll break too much :P

**Comment by Moxinilian** [comment]
AR EYOU CRAZY???????????????????????????????
i think we may have lost him

**Pull request merged**
