### PR TITLE
Add beginner-friendly sprite rendering utilities

### PR DESCRIPTION
**Pull request by Xaeroxe**
Recreation of #787 

Sorry @Moxinilian !  I've given you push access to this branch.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/804)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Oh uh btw since I can't approve a PR I opened but I didn't author this code this comment is going to serve as my approval of this PR.

**Comment by Xaeroxe** [comment]
Ok so this meets the criteria for merging at this point.  Before I do I'd like @Moxinilian to give the ok as I haven't heard anything from him since I accidentally closed his PR.

**Comment by Moxinilian** [comment]
The book update will come shortly after.

**Pull request merged**
