### PR TITLE
Update book example pong-tutorial-06 to fix clippy warning

### PR DESCRIPTION
**Pull request by MrTanoshii**
## Description

Clippy will warn of https://rust-lang.github.io/rust-clippy/master/index.html#option_as_ref_deref
The examples were already fixed by #2181 but the book was not.

## Additions

N/A

## Removals

N/A

## Modifications

N/A

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by MrTanoshii** [comment]
I got 

```
warning: called `.as_ref().map(|e| &**e)` on an Option value. This can be done more directly by calling `self.inner.source.as_deref()` instead
   --> amethyst_error\src\lib.rs:124:9
    |
124 |         self.inner.source.as_ref().map(|e| &**e)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try using as_deref instead: `self.inner.source.as_deref()`
    |
note: the lint level is defined here
   --> amethyst_error\src\lib.rs:18:9
    |
18  | #![warn(clippy::all)]
    |         ^^^^^^^^^^^
    = note: `#[warn(clippy::option_as_ref_deref)]` implied by `#[warn(clippy::all)]`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#option_as_ref_deref

warning: 1 warning emitted
```

when I ran clippy but since I do not quite understand what that piece of code does, I left it alone

**Comment by CleanCut** [comment]
> [snip] but since I do not quite understand what that piece of code does, I left it alone

No worries. That's a similar lint error in the errors module of Amethyst itself.  Perfectly fine to leave that for now and focus on cleaning up this specific example.  Thank you for the fix!  I verified it works for me.

**Comment by CleanCut** [comment]
bors +r

**Comment by CleanCut** [comment]
Hmm. It looks like the CI build failed on a transient error, but I don't have sufficient permissions to re-run the build. I'll see if I can poke someone to re-run the build.  Or you could push up some tiny commit (like adding or removing whitespace) and that would trigger a new run as well.

**Comment by CleanCut** [comment]
I was apparently wrong. CI is failing _again_ with
```
 > git checkout -f 9dc5e67a3463f9973ee7622a5d95846372ede355 # timeout=10

Could not lock repository. Please try again
```

I'm mystified. What would cause CI to not be able to retrieve the code? /cc @amethyst/tools-and-services

**Comment by CleanCut** [comment]
bors try

**Comment by MrTanoshii** [comment]
I'm seeing the other PRs also failing with the same reason, I'm guessing jenkins has a problem

**Comment by AlveLarsson** [comment]
@khionu this is the kind of issues that got me to question Jenkins, atm it creates more problems than it solves

**Comment by CleanCut** [comment]
> @khionu this is the kind of issues that got me to question Jenkins, atm it creates more problems than it solves

Perhaps it's time to give GitHub actions a try.  It's a solid CI already and improving fast.

Will bors listen if it's not the only thing in a comment? Time to find out...

bors retry

**Comment by CleanCut** [comment]
Seriously, Jenkins. You're going to be replaced if you don't start behaving.

bors retry

**Pull request merged**
