### PR TITLE
Mark children as dirty when their parents are dirty

### PR DESCRIPTION
**Pull request by jFransham**
The `Transform` processor currently doesn't update the position of children when the roots (i.e. objects without parents) are updated. This commit fixes this. This is working but I haven't written tests for it, I don't want to put that effort in if it turns out the current behaviour is desired (or if it turns out that locking the entities iterator for the whole body of the `Transform` processor is unacceptable).

### CODE REVIEW

**Comment by Aceeri** [comment]
I think this can just be fixed by moving the local.flag() to the end of the processor.

**Comment by jFransham** [comment]
I don't think I follow, that seems to be what I'm doing here already.

**Comment by Aceeri** [comment]
Oh it just looked like you were putting another loop inside the other one from the diff. Why'd you put the new iterator stuff in a variable?

**Comment by jFransham** [comment]
Just a style thing, I prefer to pull the argument out when it's getting long. I can change that though no problem.

**Pull request merged**
