### PR TITLE
 feat: Add stepping and exact input value control to animation system

### PR DESCRIPTION
**Pull request by Rhuagh**
Needs rebase when #567 is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/569)

### CODE REVIEW

**Comment by Rhuagh** [comment]
Rebased, ready now.

**Comment by torkleyy** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[amethyst_animation/src/resources.rs, line 328 at r1](https://beta.reviewable.io/reviews/amethyst/amethyst/569#-L594bKZ63cWf3JUwW_M:-L594bKZ63cWf3JUwW_N:b-xdirf1) ([raw file](https://github.com/amethyst/amethyst/blob/6fc5ca1c18ada52d97ce72cac015b6b51bd7820d/amethyst_animation/src/resources.rs#L328)):*
> ```Rust
> /// Used when doing animation stepping (i.e only move forward/backward to discrete input values)
> #[derive(Clone, Debug)]
> pub enum StepDirection {
> ```

Can you make the `repr` to `i8` and set `Forward` to `+1` and `Backward` to `-1`? That might make the code above shorter.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/569)*

**Comment by Rhuagh** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[amethyst_animation/src/resources.rs, line 328 at r1](https://beta.reviewable.io/reviews/amethyst/amethyst/569#-L594bKZ63cWf3JUwW_M:-L595asw2eExKP4Hpgi-:bh1qvmf) ([raw file](https://github.com/amethyst/amethyst/blob/6fc5ca1c18ada52d97ce72cac015b6b51bd7820d/amethyst_animation/src/resources.rs#L328)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Can you make the `repr` to `i8` and set `Forward` to `+1` and `Backward` to `-1`? That might make the code above shorter.
</blockquote></details>

Not sure, still need to do edge case handling individually so the index don't overflow/underflow.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/569)*

**Comment by Rhuagh** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[amethyst_animation/src/resources.rs, line 328 at r1](https://beta.reviewable.io/reviews/amethyst/amethyst/569#-L594bKZ63cWf3JUwW_M:-L5960L96ZHUWmktzt9W:b-q2kzh6) ([raw file](https://github.com/amethyst/amethyst/blob/6fc5ca1c18ada52d97ce72cac015b6b51bd7820d/amethyst_animation/src/resources.rs#L328)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Not sure, still need to do edge case handling individually so the index don't overflow/underflow.
</blockquote></details>

It would remove one line, that's about it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/569)*

**Comment by torkleyy** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/569#-:-L5DUZINBDTqpUO4kbbg:bnfp4nl)*

**Pull request merged**
