### PR TITLE
Add link to prefab docs

### PR DESCRIPTION
**Pull request by vektah**
This was missing from the side menu of https://amethyst.rs, is this all thats to add it?

### CODE REVIEW

**Comment by jojolepro** [comment]
I plan on reading it soon, I got the page opened

**Comment by Moxinilian** [comment]
Yeah okay, it does need some clarification before we can expose it to the public I think.

**Comment by LucioFranco** [comment]
Any updates on this, do we want to move forward with this doc or clarify it a bit?

**Comment by jojolepro** [comment]
I'll read the page this afternoon and push it forward if I don't find any errors

**Comment by jojolepro** [comment]
bors r+

I should have read that thing earlier, its actually really helpful and would have saved me time ;3
Thanks for pointing it out @vektah

**Pull request merged**
