### PR TITLE
Fixed sprite sheet format texture coordinate loading.

### PR DESCRIPTION
**Pull request by azriel91**
Discovered by `@cout970` in discord

### CODE REVIEW

**Comment by azriel91** [comment]
Woops, rookie move. I've pushed a quick fix to simply convert the `f32` types to the relevant `int` types, but does anyone have a preference on whether `SerializedSpriteSheet` and `SpritePosition` should take `u32` instead of `f32` for x, y, w, h, sheet_w, sheet_h, and i32 for offsets?

**Comment by azriel91** [comment]
> SerializedSpriteSheet should be u32 because you can't have float sizes
>
> &ndash; Jojo

> f32 was mostly to reduce casting
>
> &ndash; Moxi

> I'm using non-integer sprite offsets.
>
> ```rust
> sprite.offsets = [0.0, -3.5];
> ```
>
> On the other hand, centering 23 pixel high sprites is maybe not a common case...  
> (and it is a minor annoyance that Sprite::from_pixel_values() takes integer offsets...)
>
> &ndash; `@Swegecko`

Todo:

* [ ] `u32` for x/y/w/h
* [ ] `f32` for offsets (also update `from_pixel_values()` to take `f32`)
* [ ] Update examples (pong, sprites_ordered)
* [ ] Update book

**Comment by jojolepro** [comment]
> I'm using non-integer sprite offsets.
> 
> sprite.offsets = [0.0, -3.5];
> On the other hand, centering 23 pixel high sprites is maybe not a common case...
> (and it is a minor annoyance that Sprite::from_pixel_values() takes integer offsets...)

Sounds like a valid use case ^^

**Comment by azriel91** [comment]
I've tested these examples locally:
* sprites_ordered
* sprite_camera_follow
* pong

Can't convince seem to mdbook to test the book on Windows, so just waiting on CI.

**Comment by torkleyy** [comment]
Let's merge this then.
bors r=Moxinilian,torkleyy

**Pull request merged**
