### PR TITLE
Add Tint support for sprites in 2d

### LINKED ISSUE #1751: [NEW FEATURE] Tint support on 2D passes
`Tint` component should be respected in flat render passes, applied as color multiplication to the sprites.

This feature was unintentionally omitted when porting to new renderer, so it's a regression really.

### PR DESCRIPTION
**Pull request by ohnoimdead**
## Description

Adds Tint component support for sprites.

Fixes #1751 

## Modifications

- Change `SpriteArgs` to include a vec4 `tint` field
- Change the sprite shader to accept a vec4 color argument

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Ran `cargo test --all` locally if this modified any rs files.
- [x] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [ ] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Added unit tests for new APIs if any were added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by ohnoimdead** [comment]
fixes https://github.com/amethyst/amethyst/issues/1751

**Comment by ohnoimdead** [comment]
sprite_tint

Note about the rendy example: Tint does not implement PrefabData so I manually added some sprite entities to the rendy example to demonstrate tinting, which is why the colorized crates render at the same time as the spheres (and before everything else from the prefab scene).

**Comment by torkleyy** [comment]
It would be great if we had some kind of documentation which components are picked up by which pass.

**Comment by ohnoimdead** [comment]
> It would be great if we had some kind of documentation which components are picked up by which pass.

I was thinking that too. Is that something that should go in the book? I could add doc comments to the Tint struct, but I'm not sure that's the best place. If you point me in the right direction I can add something to this PR.

**Comment by torkleyy** [comment]
The book might be one place, but I was thinking we could add them to the API docs of the specific pass struct (e.g. `DrawFlat2DDesc`).

**Comment by azriel91** [comment]
bors r=torkleyy,azriel91

Shall get this in and let docs come in later in https://github.com/amethyst/amethyst/issues/1759 (don't want to force many rebase/merges).

**Comment by azriel91** [comment]
bors retry

```
No space left on device (os error 28)
```

**Pull request merged**
