### PR TITLE
Smooth Out Publishing

### PR DESCRIPTION
**Pull request by CleanCut**
Improvements related to the release process while going through the release process for 0.15.1.

### CODE REVIEW

**Comment by CleanCut** [comment]
https://github.com/amethyst/amethyst/pull/2437/commits/f911c8b08e960f005fc8013858a971aaa95ac2ed will need to be reverted before this PR can be merged (the commenting out of dev dependencies).

**Comment by CleanCut** [comment]
Also, this circular dev-dependencies thing is crazy weird.  That's why CI is failing (dev dependencies are commented out).  I strongly recommend we find another solution that doesn't require commenting out dev dependencies during the release process.

**Comment by Blisto91** [comment]
For automatic publishing it might be worth looking into [cargo hack.](https://crates.io/crates/cargo-hack)
It can remove dev-dependencies from a cargo.toml. It can also restore them again if that is desired.

**Comment by CleanCut** [comment]
> For automatic publishing it might be worth looking into [cargo hack.](https://crates.io/crates/cargo-hack)
> It can remove dev-dependencies from a cargo.toml. It can also restore them again if that is desired.

👍 Added it to the list on https://github.com/amethyst/amethyst/issues/2407

**Comment by CleanCut** [comment]
This is ready for review.  You can ignore the  `gitlab-ci-helper.sh → scripts/docs-helper.sh` and `scripts/publish_docs.sh` stuff -- I'll finish up those changes in a different PR -- and those were already broken/nonexistent.

**Review by erlend-sh — APPROVED** [review]

**Pull request merged**
