### PR TITLE
Add part 3 to the pong example in the book

### PR DESCRIPTION
**Pull request by akatechis**
This PR adds part 3 to the pong example in the book- guides the user towards adding a system that receives input from an `InputHandler` and moves the paddles.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/571)

### CODE REVIEW

**Comment by Rhuagh** [comment]
bors try

**Comment by Rhuagh** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 135 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5ItJkzWHfQcgIL-oZe:-L5ItJkzWHfQcgIL-oZf:b8zso5v) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L135)):*
> ```Markdown
> 
> ## Summary
> In this chapter, we created added an input handler to our game, so that we could capture keypresses. We then added a system that would interpret these keypresses, and move our game's paddles accordingly. In the next chapter, we'll explore another key concept in real-time games: time. We'll make our game aware of time, and add a ball for our paddles to bounce back and forth.
> ```

`created added`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by torkleyy** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 3 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JmVzREtLlaLT2AF-c:-L5JmVzREtLlaLT2AF-d:bamege0) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L3)):*
> ```Markdown
> # Moving the paddles
> 
> In the previous chapter, we learned about the relationship between entities and components, and how they represent the "things" in our games. This chapter introduces Systems— the S in "ECS". Systems are objects that represent operations over entities, or more specifically, combinations of components. Let's add a system that moves the paddles based on user input.
> ```

Please use line breaks;
"and how they represent things in our games": maybe "how they can be used to structure a game" might be better?;
"Systems- the": missing space before "-"

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 5 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5Jn27LX9IxGC11D6tt:-L5Jn27MNBrOZ8CHlANw:b24t62m) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L5)):*
> ```Markdown
> In the previous chapter, we learned about the relationship between entities and components, and how they represent the "things" in our games. This chapter introduces Systems— the S in "ECS". Systems are objects that represent operations over entities, or more specifically, combinations of components. Let's add a system that moves the paddles based on user input.
> 
> A system is nothing more than a function that runs once each frame and potentially makes some changes to components. If you've used other game engines, this probably sounds familiar: Unity engine calls these objects as `MonoBehaviour`s and Unreal engine calls them `Actor`s, but these all represent the same basic idea.
> ```

I'm unsure if this is a good explanation here, there's a fundamental difference of `MonoBehavior`s and `System`s. I can't clearly say if `MonoBehavior` is more like a `Component` or a `System`, that's an indicator this might be confusing.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 7 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JnbbyrZVBT4lk_0_P:-L5JnbbyrZVBT4lk_0_Q:bsn4ut3) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L7)):*
> ```Markdown
> A system is nothing more than a function that runs once each frame and potentially makes some changes to components. If you've used other game engines, this probably sounds familiar: Unity engine calls these objects as `MonoBehaviour`s and Unreal engine calls them `Actor`s, but these all represent the same basic idea.
> 
> Systems in specs/amethyst are slightly different. Rather than describe the functionality of a single component, they describe the functionality of all components of a specific type. This difference impacts the runtime performance of a game, since it lets us optimize the way the components are stored with cache-locality in mind. It also means we can make systems run in parallel when they don't share any data between them.
> ```

Specs/Amethyst; "Rather than describing".

content-wise: I think that's a bit imprecise as it sounds like there's a system <-> component type relation ship, but there isn't. Systems are just describing data transformations or how components interact, they don't have to be centered around a single type and there may exist multiple systems only accessing one specific component type.
I think the note about optimization should be removed, it confuses beginners. _Maybe_ put a link here, but it needs a more detailed explanation.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 18 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JodaajBYAitXJRwTp:-L5JodaajBYAitXJRwTq:bhht1qo) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L18)):*
> ```Markdown
>   axes: {
>     "left_paddle": (pos: Key(W), neg: Key(S)),
>     "right_paddle": (pos: Key(Up), neg: Key(Down))
> ```

missing trailing comma

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 24 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JofPgpEEdC_HdEXt8:-L5JofPgpEEdC_HdEXt9:b-5jfoj3) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L24)):*
> ```Markdown
> ```
> 
> In amethyst, inputs can be either scalar inputs (eg, a button that is pressed or not), or axes (eg, a range that relates two buttons as opposite ends of a range). In this file, we're creating two axes: W,S will move the left paddle up and down, and the Up and Down arrow keys will move the right paddle up and down.
> ```

"e.g." (twice);
Amethyst
W and S

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 32 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5Jp0SAXBTx3nI_Yp80:-L5Jp0SAXBTx3nI_Yp81:babx2a2) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L32)):*
> ```Markdown
> 
> let input_bundle = InputBundle::<String, String>::new()
> .with_bindings_from_file("./resources/bindings.ron");
> ```

Missing indentation

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 35 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5Jp76lN26K9YpA_i_i:-L5Jp76lN26K9YpA_i_j:bnj7hl0) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L35)):*
> ```Markdown
> 
> let mut game = Application::build("./", Pong)?
> .with_bundle(TransformBundle::new())?
> ```

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by Xaeroxe** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 3 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JmVzREtLlaLT2AF-c:-L5K0mSx8SiI_ROqibAw:b-olxrl3) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L3)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Please use line breaks;
"and how they represent things in our games": maybe "how they can be used to structure a game" might be better?;
"Systems- the": missing space before "-"
</blockquote></details>

So to be clear, we prefer lines that are about 100 characters long.  Please line break when you get to about 100 characters in your line.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 5 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5Jn27LX9IxGC11D6tt:-L5K0PW-K26KMtugVrA0:bdpm276) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L5)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

I'm unsure if this is a good explanation here, there's a fundamental difference of `MonoBehavior`s and `System`s. I can't clearly say if `MonoBehavior` is more like a `Component` or a `System`, that's an indicator this might be confusing.
</blockquote></details>

I agree with torkleyy.  I'm all for trying to draw similarities to existing and well understood concepts but to say a `System` is like a `MonoBehaviour` could result in the reader having some of the wrong ideas.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 7 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JnbbyrZVBT4lk_0_P:-L5K1-iaa4Mq3vTZHoFm:b3d0mzu) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L7)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Specs/Amethyst; "Rather than describing".

content-wise: I think that's a bit imprecise as it sounds like there's a system <-> component type relation ship, but there isn't. Systems are just describing data transformations or how components interact, they don't have to be centered around a single type and there may exist multiple systems only accessing one specific component type.
I think the note about optimization should be removed, it confuses beginners. _Maybe_ put a link here, but it needs a more detailed explanation.
</blockquote></details>

I actually kind of like the optimization note as it provides motivation to use Amethyst.  That being said, maybe it's enough to say "this runs faster" and then link to a more in-depth explanation of why this data model is better for performance.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 18 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JodaajBYAitXJRwTp:-L5K239cKbHGdTq0Mg7i:b-2e55ik) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L18)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

missing trailing comma
</blockquote></details>

Note to the author: This isn't correct in our repo either.  We just want to do better from here forward.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 42 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K2UvoYF0jlsgFplh7:-L5K2UvoYF0jlsgFplh8:b-rojkch) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L42)):*
> ```Markdown
> ```
> 
> At this point, we're ready to write a system that reads input from the input handler, and moves the paddles accordingly. First, we'll create a directory called `systems` under `src` to hold all our systems. We'll use a module to collect and export each of our systems to the rest of the application. Here's our `mod.rs` for `src/systems`:
> ```

This might be a good opportunity to connect this to a concrete type by saying `InputHandler` rather than "input handler".

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 88 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K2l4Bu_jDBMD6U-_i:-L5K2l4Bu_jDBMD6U-_j:b-d7d42s) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L88)):*
> ```Markdown
> Let's review what our system does, because there's quite a bit there.
> 
> We create a unit struct, called PaddleSystem, and implement the System trait for it. The trait specifies the lifetime of the components on which it operates. Inside the implementation, we define the `SystemData` the system operates on, a tuple of `WriteStorage`, `ReadStorage`, and `Fetch`. More specifically, the generic types we've used here tell us that the `PaddleSystem` mutates LocalTransform components, `WriteStorage<'s, LocalTransform>`, it reads `Paddle` components, `ReadStorage<'s, Paddle>`, and also accesses the `InputHandler<String, String>` resource we created earlier, using the `Fetch` trait.
> ```

Please add backticks that surround any type name.  Later on in this line you do pretty good with this but the first few were missed.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 90 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K2yhvoyUWpxalcYCm:-L5K2yhvoyUWpxalcYCn:bls51yo) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L90)):*
> ```Markdown
> We create a unit struct, called PaddleSystem, and implement the System trait for it. The trait specifies the lifetime of the components on which it operates. Inside the implementation, we define the `SystemData` the system operates on, a tuple of `WriteStorage`, `ReadStorage`, and `Fetch`. More specifically, the generic types we've used here tell us that the `PaddleSystem` mutates LocalTransform components, `WriteStorage<'s, LocalTransform>`, it reads `Paddle` components, `ReadStorage<'s, Paddle>`, and also accesses the `InputHandler<String, String>` resource we created earlier, using the `Fetch` trait.
> 
> It's worth noting an important difference between the objects our system accesses. A system will iterate over entities that contain one of each of the components that it specifies in its SystemData. Going back to our example, the PaddleSystem will ignore any entity that is missing a `Paddle`, `LocalTransform` or both.
> ```

Missing backticks

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 104 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K3RM6jutTDseD7VZL:-L5K3RM6jutTDseD7VZM:bi1cpkz) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L104)):*
> ```Markdown
>       };
>       if let Some(mv_amount) = movement {
>         let scaled_amount = (1.0 / 60.0) * mv_amount as f32;
> ```

Hardcoding a framerate of 60 is a very bad practice that we shouldn't even be suggesting from the start.  Let's take the time to teach the user how to do this right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by Xaeroxe** [comment]
*[book/src/pong_tutorial/pong_tutorial_03.md, line 18 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JodaajBYAitXJRwTp:-L5K50g-rDxXeQhCH96g:bxua9a1) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L18)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

Note to the author: This isn't correct in our repo either.  We just want to do better from here forward.
</blockquote></details>

Ok I guess we've fixed this in our repo.  At one point it wasn't correct though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by torkleyy** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 3 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JmVzREtLlaLT2AF-c:-L5K9pqZ3nQtHLB01IWz:b-mju1ov) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L3)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

So to be clear, we prefer lines that are about 100 characters long.  Please line break when you get to about 100 characters in your line.
</blockquote></details>

It says 80 in the CONTRIBUTING.md: https://github.com/amethyst/amethyst/blob/develop/CONTRIBUTING.md#writing-documentation
That's also what I am using.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 7 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5JnbbyrZVBT4lk_0_P:-L5KA23lyb20aVspg415:b-lnn24b) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L7)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

I actually kind of like the optimization note as it provides motivation to use Amethyst.  That being said, maybe it's enough to say "this runs faster" and then link to a more in-depth explanation of why this data model is better for performance.
</blockquote></details>

Yep :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by Rhuagh** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 104 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K3RM6jutTDseD7VZL:-L5O0EBFpQc0-EiKTHKq:br74u8o) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L104)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

Hardcoding a framerate of 60 is a very bad practice that we shouldn't even be suggesting from the start.  Let's take the time to teach the user how to do this right.
</blockquote></details>

I believe this is touched upon in the text below, the next chapter will be primarily geared towards time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by malikolivier** [comment]
*[book/src/pong_tutorial/pong_tutorial_03.md, line 135 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5ItJkzWHfQcgIL-oZe:-L6zQmT0HlbJN01pbrDg:blsesvg) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L135)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

`created added`
</blockquote></details>

Newbie who just started to take a look at Amethyst here. Thanks for writing the chapter, I just went through it.

It seems to me that`PaddleSystem` should be included when building an `Application` somewhere.

This is not explained here. If I run the code as explained in this PR,  no key press will be logged, and the paddles will not move.

Maybe something similar (but simpler) to [this](https://github.com/amethyst/amethyst/blob/0662e54eaa8db24be80b1ca9cb0f87329f8ac720/examples/pong/bundle.rs#L23) should be included in this chapter.

Please correct me if I am wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by akatechis** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 5 at r1](https://beta.reviewable.io/reviews/amethyst/amethyst/571#-L5Jn27LX9IxGC11D6tt:-L8J-iRw5VNNMLjMnLyj:bwygb03) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L5)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

I agree with torkleyy.  I'm all for trying to draw similarities to existing and well understood concepts but to say a `System` is like a `MonoBehaviour` could result in the reader having some of the wrong ideas.
</blockquote></details>

Would you guys say that even with the clarification, it can lead to confusion? I felt it would be helpful to explain that they're analogous to each other (since they contain the behavior of the game), even though it's not a 1:1 analogy. I can clarify that a system doesn't deal with a single instance but all instances of a specific type: rather than being concerned with a single enemy, a system would be responsible for all enemies in the game world.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 104 at r1](https://beta.reviewable.io/reviews/amethyst/amethyst/571#-L5K3RM6jutTDseD7VZL:-L8J98_wD5bTwSYhcEGb:bpypqtb) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L104)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

I believe this is touched upon in the text below, the next chapter will be primarily geared towards time.
</blockquote></details>

Correct. I figured there was enough here that adding time/framerate stuff might make the chapter excessively long? Maybe I can add a note that this is not the correct way to do it, why it's wrong, and how it will be fixed in the next chapter.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/571)*

**Comment by Rhuagh** [comment]
Are you planning on adding a pong_tutorial_03 with the actual code also or?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/571#-:-L8OU5-7DgFL5mLZKSRU:bag7sia)*

**Comment by akatechis** [comment]
I was under the impression that the examples crate already had a completed version of pong, so the book just needed a writeup explaining how to get from a blank repo to the game, and explain it along the way.

---

Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/571#-:-L8PdOZr6VMq-JR38Jty:bg2okfo)*

**Comment by akatechis** [comment]
Ignore the last comment. Last time I scanned the directory I saw `pong` which had the complete implementation, but I suppose I neglected to notice the incremental examples. Will add it ASAP.

---

Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/571#-:-L8PecYiCpscgIcXEk-b:b-odwqhc)*

**Comment by torkleyy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 5 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5Jn27LX9IxGC11D6tt:-L8RugtxEXOd3TZN6yav:b32w0x) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L5)):*
<details><summary><i>Previously, akatechis (Alexandros Katechis) wrote…</i></summary><blockquote>

Would you guys say that even with the clarification, it can lead to confusion? I felt it would be helpful to explain that they're analogous to each other (since they contain the behavior of the game), even though it's not a 1:1 analogy. I can clarify that a system doesn't deal with a single instance but all instances of a specific type: rather than being concerned with a single enemy, a system would be responsible for all enemies in the game world.
</blockquote></details>

OK

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 42 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K2UvoYF0jlsgFplh7:-L8RvRMFWMHBDtn0PWj3:b9zlnf2) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L42)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

This might be a good opportunity to connect this to a concrete type by saying `InputHandler` rather than "input handler".
</blockquote></details>

I think this is done.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 88 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K2l4Bu_jDBMD6U-_i:-L8RvZb91iUSg-tTFf6f:bb6ywmx) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L88)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

Please add backticks that surround any type name.  Later on in this line you do pretty good with this but the first few were missed.
</blockquote></details>

LGTM

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 90 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K2yhvoyUWpxalcYCm:-L8Rvd8OlBxWRRa-RIZR:bb6ywmx) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L90)):*
<details><summary><i>Previously, Xaeroxe (Jacob Kiesel) wrote…</i></summary><blockquote>

Missing backticks
</blockquote></details>

LGTM

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 104 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K3RM6jutTDseD7VZL:-L8RvjxAc1pVy1DCxnrg:b271ee9) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L104)):*
<details><summary><i>Previously, akatechis (Alexandros Katechis) wrote…</i></summary><blockquote>

Correct. I figured there was enough here that adding time/framerate stuff might make the chapter excessively long? Maybe I can add a note that this is not the correct way to do it, why it's wrong, and how it will be fixed in the next chapter.
</blockquote></details>

Yeah, please add a comment here that it's bad practice.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 11 at r2](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L8RusehnpAQQoW3lpQI:-L8RusehnpAQQoW3lpQJ:bb7ve1f) ([raw file](https://github.com/amethyst/amethyst/blob/e2681fcfc4c3fee552df000a3d25d532d10ccaf6/book/src/pong_tutorial/pong_tutorial_03.md#L11)):*
> ```Markdown
> A system is nothing more than a function that runs once each frame and
> potentially makes some changes to components. If you've used other game
> engines, this probably sounds familiar: Unity engine calls these objects as
> ```

~as~

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 22 at r2](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L8Rv4hJxANtQhjrdM0W:-L8Rv4hJxANtQhjrdM0X:b-i3venf) ([raw file](https://github.com/amethyst/amethyst/blob/e2681fcfc4c3fee552df000a3d25d532d10ccaf6/book/src/pong_tutorial/pong_tutorial_03.md#L22)):*
> ```Markdown
> Let's get started.
> 
> ## Capturing user input
> ```

Missing newline

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 73 at r2](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L8RvXPqTRY3BDVmrSqk:-L8RvXPqTRY3BDVmrSql:bls51yo) ([raw file](https://github.com/amethyst/amethyst/blob/e2681fcfc4c3fee552df000a3d25d532d10ccaf6/book/src/pong_tutorial/pong_tutorial_03.md#L73)):*
> ```Markdown
> ```
> 
> We're finally ready to implement the PaddleSystem:
> ```

Missing backticks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by Rhuagh** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by Rhuagh** [comment]
Fix the last remaining nits and then we're good to go imho :)

---

Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571#-:-L8TqcOrd1lWdM8tv7Ny:b-o9s72t)*

**Comment by torkleyy** [comment]
Looks good to me, with the exception of the hardcoded fps.

---

Reviewed 1 of 9 files at r3, 10 of 11 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 104 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K3RM6jutTDseD7VZL:-L8V_NgRcuMCyRkXoJ0I:bn3phlc) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L104)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Yeah, please add a comment here that it's bad practice.
</blockquote></details>

I think you missed this one ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571#-:-L8V_UI2yDh7Ac2j5lE2:b-cz8s6i)*

**Comment by Rhuagh** [comment]
Reviewed 10 of 11 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by akatechis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 104 at r1](https://reviewable.io:443/reviews/amethyst/amethyst/571#-L5K3RM6jutTDseD7VZL:-L8YmPLZBbt7kDTNncus:b11k7t6) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L104)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

I think you missed this one ;)
</blockquote></details>

Not sure why it's not showing up here, but when I look at my fork, I see the comment about hardcoding the framerate (https://github.com/akatechis/amethyst/blame/develop/book/src/pong_tutorial/pong_tutorial_03.md#L167)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amethyst/amethyst/571)*

**Comment by Rhuagh** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[book/src/pong_tutorial/pong_tutorial_03.md, line 104 at r1](https://beta.reviewable.io/reviews/amethyst/amethyst/571#-L5K3RM6jutTDseD7VZL:-L8hu8ZT3pQ6mIANZUep:b-6a21ox) ([raw file](https://github.com/amethyst/amethyst/blob/e8221253dd196147801571db42b96674423fe80b/book/src/pong_tutorial/pong_tutorial_03.md#L104)):*
<details><summary><i>Previously, akatechis (Alexandros Katechis) wrote…</i></summary><blockquote>

Not sure why it's not showing up here, but when I look at my fork, I see the comment about hardcoding the framerate (https://github.com/akatechis/amethyst/blame/develop/book/src/pong_tutorial/pong_tutorial_03.md#L167)
</blockquote></details>

If you expand the section below this comment you'll see the text in question.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/amethyst/amethyst/571)*

**Comment by jojolepro** [comment]
Ready to merge?

**Comment by Rhuagh** [comment]
Should be

**Comment by Xaeroxe** [comment]
:shipit: 

bors r+

**Pull request merged**
