### PR TITLE
Fix paths in book links

### PR DESCRIPTION
**Pull request by gmorenz**
Just fixing some broken links.

#1326 which sounds similar isn't.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4b9a52830263a5c2aaa93061b8c4a55141aca553
  * Your commit message does not contain a body

Guidelines are available at https://github.com/amethyst/amethyst

---
This message was auto-generated by https://gitcop.com

**Comment by gmorenz** [comment]
Added a body to the commit message...

**Comment by azriel91** [comment]
Thanks for this! and wow, didn't know we had something policing git 👮

**Comment by azriel91** [comment]
bors r=azriel91,Xaeroxe

@gmorenz btw we disabled @GitCop, still working out what to do with it

**Pull request merged**
