### PR TITLE
Allow use of reexported legion crate for codegen

### PR DESCRIPTION
**Pull request by luckystreak63**
## Description
This change allows amethyst users to use legion codegen without needing to add the legion crate to their Cargo.toml.

## Motivation and Context

This change reduces the friction involved in using legion codegen.
The compiler will correctly identify what to import to make it work.

## How Has This Been Tested?

This has been tested locally by compiling a personal project and the amethyst animation example.

## Checklist:

- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [x] My code follows the code style of this project.
- [x] If my change required a change to the documentation I have updated the documentation accordingly.
- [x] I have updated the content of the book if this PR would make the book outdated.
- [ ] I have added tests to cover my changes.
- [ ] My code is used in an example.

### CODE REVIEW

**Comment by luckystreak63** [comment]
Examples pong_02 and pong_06 work with this change, and the reexport feature works with my personal project as well.

**Comment by luckystreak63** [comment]
Examples pong_02 and pong_06 work with this change, and the reexport feature works with my personal project as well.

**Comment by luckystreak63** [comment]
@AlveLarsson

**Review by AlveLarsson — APPROVED** [review]
Thanks! 👍

**Pull request merged**
