### PR TITLE
Added pass for PosColor

### PR DESCRIPTION
**Pull request by norman784**
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/1183)

### CODE REVIEW

**Comment by jojolepro** [comment]
I'd like to review this in details before it gets merged. I want to see if its mergeable into the DrawFlat2D pass.

**Comment by Rhuagh** [comment]
This and Flat have different vertex buffer layouts, so it needs to be a separate pass, so i'm ok with this being pushed.

**Comment by norman784** [comment]
Seems that the fork I've is quite old, and don't know how to update my fork without doing a mess with the changes I made.

**Comment by jojolepro** [comment]
oh I missed that message.

```
git remote add upstream https://github.com/amethyst/amethyst
git pull upstream master
```

It will list the file that have merge issues. You go in them and fix the merge (stuff between >>>>> and <<<<<).

Then
```
git merge --continue
git push
```

**Comment by fhaynes** [comment]
@jojolepro or @happenslol can you please fix and merge this or close it?

**Comment by fhaynes** [comment]
@norman784 looks like quite a few failures. Did you want to work through them? If so, I'd suggest a clean fork and PR, as this one is now, er, cluttered. Ping me on Discord if you want, and I'll see if I can help or find someone who can.

**Comment by norman784** [comment]
Yes, I agree, my PR was too old, I'll do a clean fork and reimplement the pass the weekend.

**Comment by fhaynes** [comment]
@norman784 awesome, thanks. I'll close this one then.

**Pull request closed without merging**
