### PR TITLE
Switch from timing::Time to game_clock::Time

### PR DESCRIPTION
**Pull request by jojolepro**
## Description
Changes from our custom Time struct to the simplified version in the game_clock crate.

Functions are not the same but pretty similar. There were only ~10 cases where code needed to be changed.

## Motivation and Context
Less code to maintain :)

## How Has This Been Tested?
cargo test --all-targets

## Checklist:
- [X] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [X] My code follows the code style of this project.
- [ ] If my change required a change to the documentation I have updated the documentation accordingly.
- [ ] I have updated the content of the book if this PR would make the book outdated.
- [ ] I have added tests to cover my changes.
- [ ] My code is used in an example.

### CODE REVIEW

**Review by AlveLarsson — APPROVED** [review]
Thanks, Joel!

**Comment by jojolepro** [comment]
bors r+

BlessRNG

**Comment by jojolepro** [comment]
bors retry

**Comment by jojolepro** [comment]
thanks bot, I love you too

**Comment by jojolepro** [comment]
Merged because it only fails on nightly and clippy checks.

**Pull request merged**
