### PR TITLE
Changed the required Vec<u8> to &[u8] on texture loading

### PR DESCRIPTION
**Pull request by Debily**
Addressing [this](https://github.com/amethyst/amethyst/issues/900) issue.

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/901)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
I don't see a terribly compelling reason to take a self reference in these signatures either.  Can we remove those?

**Comment by Xaeroxe** [comment]
> Eventually we might just replace Vec in SimpleFormat by &[u8]

Btw IIRC we had this discussion when designing the Format API originally, and the conclusion we came to was essentially "The asset system has no further use for the raw data, so why not allow the format to take ownership of it?"  Indeed for some formats this turned out to be a good thing as we were able to avoid unnecessary memory copies of large texture assets.

**Comment by jojolepro** [comment]
So is this PR good as it is? @Xaeroxe

**Comment by Xaeroxe** [comment]
This PR seems to be an improvement to the functions provided.  If we wanted to go the extra mile we should also remove the `&self` in these function signatures, as taking a `&self` where self is a unit structure is kind of silly.

**Comment by jojolepro** [comment]
@Debily Do you want to do that or we merge this like it is now?

**Comment by Debily** [comment]
It's weird that some checks fail. I followed the contributing guidelines without any encounter of error.

**Comment by Xaeroxe** [comment]
@Moxinilian can you weigh in here?

**Comment by Moxinilian** [comment]
Well I think you first need to solve the merge conflict.
Then, if it does not solve the issue, I'll see what AppVeyor is trying to do.

**Comment by Moxinilian** [comment]
bors retry

**Comment by Moxinilian** [comment]
Could you please rebase this pull request with the develop branch? We changed some of bors' settings so you need to update them in your fork so that it can merge it correctly.

**Pull request merged**
