### PR TITLE
Make main functions return Results

### PR DESCRIPTION
**Pull request by vitvakatu**
Rust 1.26 supports returning Results from `main()`. Good time to get rid of `run()` functions!

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/712)

### CODE REVIEW

**Comment by torkleyy** [comment]
I think using new-ish features in the examples is fine, but the project
should build with older versions of Rust, too. We should ensure (using CI)
that the build works for 1.23.

**Comment by vitvakatu** [comment]
Well, it will not work on Rust 1.23 (and any other stable prior to 1.26). Personally I don't think it's a problem, as we support stable toolchain.

**Comment by torkleyy** [comment]
As I said, only the build has to work on 1.23, the examples may use the
latest version.

**Comment by Xaeroxe** [comment]
@torkleyy Rust is still a budding language with lots of valuable features to come.  rustc itself is still in active development, it'd be a shame to lock ourselves down so soon imo.  Why 1.23 specifically?

**Comment by torkleyy** [comment]
Latest version - 3, that's the minimum I chose for me personally. So every six weeks we can bump that version.

**Comment by jojolepro** [comment]
My opinion is that we can safely follow rust stable latest version. Reason: Its "stable". Nothing is going to break except if you don't rustup update.

**Comment by torkleyy** [comment]
> except if you don't rustup update.

That's kind of the point here. I don't want to break anyone's build because a new patch uses a very new feature.

**Comment by Rhuagh** [comment]
I agree with @Xaeroxe here, 1 version behind seems fine to me.

**Comment by torkleyy** [comment]
Also fine for me

**Comment by jojolepro** [comment]
I guess

**Comment by jojolepro** [comment]
Status: Postponed until rust stable version 1.27 is released.

**Comment by omni-viral** [comment]
If we will release once in 6 weeks as well than we can follow stable Rust immediately in development.
Use 1.26 features now and release when 1.27 out.

**Comment by omni-viral** [comment]
@torkleyy if urgent we can release without waiting since we still use only stable. And after few weeks most people have updated compiler anyway.

**Comment by Xaeroxe** [comment]
@vitvakatu Seems PR #691 hit this pretty hard.  Can you rebase it?

**Pull request closed without merging**
