### PR TITLE
Add missing tab order parameter in book (release)

### PR DESCRIPTION
**Pull request by torkleyy**
## Description

Added missing parameter to book (release version). Problem was reported in #506.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Ran `cargo test --all` locally if this modified any rs files.
- [x] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [x] Updated the content of the book if this PR would make the book outdated.
- [x] ~~Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.~~
- [x] Added unit tests for new APIs if any were added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

**Comment by torkleyy** [comment]
I'm currently unsure if the website will be updated when this is merged into 0.10. I'll look it up if I don't forget to.

**Comment by torkleyy** [comment]
Ah, seems to be tag dependent: https://github.com/amethyst/website/blob/master/generate.sh#L89

**Comment by LucioFranco** [comment]
@torkleyy you will have to make a new tag and the release that, then we need to make sure we point to that tag for docs and the book and the website _should_ build all versions of the book nightly.

**Comment by Moxinilian** [comment]
bors retry

**Comment by Moxinilian** [comment]
@torkleyy I think you might want to rebase to update the CI configurations.

**Comment by fhaynes** [comment]
Yikes, missed the rebase. Closing this one, will have to make a new one to do this now.

**Pull request closed without merging**
