### PR TITLE
Add missing cmake dependency to instructions

### PR DESCRIPTION
**Pull request by torkleyy**
Seems nobody used such a fresh system to build Amethyst yet ^^

### CODE REVIEW

**Comment by torkleyy** [comment]
Freetype seems to be missing too. Not sure if that comes preinstalled on Ubuntu?

**Comment by torkleyy** [comment]
also missing `expat-devel`

**Comment by Moxinilian** [comment]
Do you want to add those dependencies to the list as well?

**Comment by jojolepro** [comment]
Its pretty rare for a dev to not have cmake already installed ;)
I guess it could happen on a build VM though.

**Comment by torkleyy** [comment]
@jojolepro As I've said, fresh install.

@Moxinilian done.

**Comment by torkleyy** [comment]
bors r=jojolepro,Moxinilian

**Comment by Moxinilian** [comment]
What's the difference between `bors r+` and `bors r=jojolepro,Moxinilian`?

**Comment by torkleyy** [comment]
Specifies reviewers to bors so I can blame you for any mistakea :P

On Sep 30, 2018 12:37, "Théo Degioanni" <notifications@github.com> wrote:

What's the difference between bors r+ and bors r=jojolepro,Moxinilian?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amethyst/amethyst/pull/973#issuecomment-425711216>, or mute
the thread

**Comment by torkleyy** [comment]
A bors r+ makes yourself the reviewer, which is not always the case.

**Pull request merged**
