### PR TITLE
Update amethyst_core to legion 0.3

### PR DESCRIPTION
**Pull request by LechintanTudor**
## Description
Transition systems and other functionalities to legion 0.3 and update various outdated crates.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Updated the content of the book if this PR would make the book outdated.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --workspace --features "empty"` (may require `cargo clean` before)
- [x] Ran `cargo build --features "empty"`
- [x] Ran `cargo test --workspace --features "empty"`

### CODE REVIEW

**Comment by CleanCut** [comment]
Please remember to add changelog entries for the _notable_ dependencies that you change/update (and check for usage/breakage in other subcrates that use them). 😄

**Comment by valkum** [comment]
LGTM

**Comment by CleanCut** [comment]
I pushed up commits to:
- publicly re-export `simba` as `amethyst_core::simd`
- fix a couple things that broke in `amethyst_rendy`

**Comment by AlveLarsson** [comment]
Is this ready for merge? :)

**Comment by CleanCut** [comment]
@AlveLarsson Yes, I just wanted to see if it would happen to pass CI.  Clippy compiles everything, though, so no luck there. I manually made sure that the minimal features build of `amethyst` builds (that's how I discovered the `amethyst_rendy` breakage to fix).

**Pull request merged**
