### PR TITLE
Reduce Travis workload by only building with bors

### PR DESCRIPTION
**Pull request by torkleyy**

### CODE REVIEW

**Comment by torkleyy** [comment]
Well, with all the activity we're having on the repo and the slow builds I think it makes sense if you're building PRs yourself. `bors try` can still be used to do that before the approval.

**Comment by torkleyy** [comment]
I'm not 100% sure either, but with the changed situation I thought it makes sense because it speeds up the merging with bors (no other PR will block the build).

**Comment by Moxinilian** [comment]
I understand the rationale, but I don't feel it's worth it.
Besides faster bors, why do we need this?
I like fast CI because I can get feedback fast, but bors being a bit slow is okay to me. To me CI speed is the most useful when you are still (potentially) working on the PR, not when you fired (and forgot) the merging process.

**Comment by torkleyy** [comment]
Convinced.

**Pull request closed without merging**
