### PR TITLE
WASM: Chip away at crashes.

### PR DESCRIPTION
**Pull request by azriel91**
## Description

Part of #2228.

## PR Checklist

By placing an x in the boxes I certify that I have:

- **n/a** Updated the content of the book if this PR would make the book outdated.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- **n/a** Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [ ] Ran `cargo +stable fmt --all`
- [ ] Ran `cargo clippy --all --features "empty"`
- [ ] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by jojolepro** [comment]
@azriel91 Do you want to update this and merge it or do you prefer closing it?

**Comment by azriel91** [comment]
I don't have time to update it; we can close it, but I think it's important that the branch remain -- there are changes and many investigations that a future attempt should find valuable.

**Comment by ezpuzz** [comment]
@jojolepro I'd love to keep this open for contributors to add to, it's a good spike at wasm/webgl support and that's an important feature on the roadmap.  Rendy has been updated on master now to gfx 0.5 and maybe that would enable this.

I will be taking a shot at getting this up to date after 0.16

**Comment by ezpuzz** [comment]
Also this PR isn't that old: https://github.com/amethyst/winit/pull/1

**Review by AnneKitsune — APPROVED** [review]
Hi! I'm wondering if it would be best to merge the couple of fixes in this PR, even though it might not fix all wasm issues. What do you think?

**Pull request closed without merging**
