### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by torkleyy**
* Avoid warnings when formatting
* ~~Remove file logging from animation example~~
* Add "Amethyst Foundation" as author

### CODE REVIEW

**Comment by azriel91** [comment]
ah, `merge_imports` isn't going to be stable any time soon https://github.com/rust-lang/rustfmt/issues/3362

if people still want it, they can add it to `rustfmt.toml` in a parent directory.

**Comment by Frizi** [comment]
Having `merge_imports` in the settings makes it more official that it should be used, even if not strictly required. Also it's used by default for everyone on nightly (and you can use `cargo +nightly fmt` if you use stable compiler). If we will remove it, it's likely that people who use it will have much more noise in their PRs due to random reformats.

I see the point about it being unstable though, the linked issue shows an edge case where it breaks currently. I have never had an issue with that personally though.

Can we somehow remove the warnings without disabling the rule for nightly fmt?

**Comment by torkleyy** [comment]
> Can we somehow remove the warnings without disabling the rule for nightly fmt?

Hmm, not sure. I don't think we can.

**Comment by azriel91** [comment]
There's this:

```bash
$ cargo +stable fmt
Warning: can't set `merge_imports = true`, unstable features are only available in nightly channel.
# ... x100

$ cargo +stable fmt 2> >(grep -vF merge_imports)
# all good
```

**Comment by torkleyy** [comment]
That looks... slightly too complicated :smile:

**Comment by torkleyy** [comment]
Removed the commit.

**Comment by torkleyy** [comment]
bors r=Frizi,azriel91

**Pull request merged**
